static struct{S k;Tk t;}KW[]={{Z("abort"),T_AB},{Z("abs"),T_ABS},{Z("accept"),T_ACC},{Z("access"),T_ACCS},{Z("all"),T_ALL},{Z("and"),T_AND},{Z("array"),T_ARR},{Z("at"),T_AT},{Z("begin"),T_BEG},{Z("body"),T_BOD},{Z("case"),T_CSE},{Z("constant"),T_CONST},{Z("declare"),T_DEC},{Z("delay"),T_DEL},{Z("delta"),T_DELTA},{Z("digits"),T_DIG},{Z("do"),T_DO},{Z("else"),T_ELSE},{Z("elsif"),T_ELSIF},{Z("end"),T_END},{Z("entry"),T_ENT},{Z("exception"),T_EXCP},{Z("exit"),T_EXIT},{Z("for"),T_FOR},{Z("function"),T_FUN},{Z("generic"),T_GEN},{Z("goto"),T_GOTO},{Z("if"),T_IF},{Z("in"),T_IN},{Z("is"),T_IS},{Z("limited"),T_LIM},{Z("loop"),T_LOOP},{Z("mod"),T_MOD},{Z("new"),T_NEW},{Z("not"),T_NOT},{Z("null"),T_NULL},{Z("of"),T_OF},{Z("or"),T_OR},{Z("others"),T_OTH},{Z("out"),T_OUT},{Z("package"),T_PKG},{Z("pragma"),T_PGM},{Z("private"),T_PRV},{Z("procedure"),T_PROC},{Z("raise"),T_RAS},{Z("range"),T_RNG},{Z("record"),T_REC},{Z("rem"),T_REM},{Z("renames"),T_REN},{Z("return"),T_RET},{Z("reverse"),T_REV},{Z("select"),T_SEL},{Z("separate"),T_SEP},{Z("subtype"),T_SUB},{Z("task"),T_TSK},{Z("terminate"),T_TER},{Z("then"),T_THEN},{Z("type"),T_TYP},{Z("use"),T_USE},{Z("when"),T_WHN},{Z("while"),T_WHI},{Z("with"),T_WITH},{Z("xor"),T_XOR},{N,T_EOF}};
static Tk kl(S s){for(int i=0;KW[i].k.s;i++)if(si(s,KW[i].k))return KW[i].t;return T_ID;}
static Lx ln(const char*s,size_t z,const char*f){return(Lx){s,s,s+z,1,1,f};}
static char pk(Lx*l){return l->c<l->e?*l->c:0;}
static char p2(Lx*l){return l->c+1<l->e?l->c[1]:0;}
static char p3(Lx*l){return l->c+2<l->e?l->c[2]:0;}
static char av(Lx*l){if(l->c>=l->e)return 0;char c=*l->c++;if(c=='\n'){l->ln++;l->cl=1;}else l->cl++;return c;}
static void sw(Lx*l){for(;;){while(l->c<l->e&&(*l->c==' '||*l->c=='\t'||*l->c=='\n'||*l->c=='\r'))av(l);if(l->c+1<l->e&&l->c[0]=='-'&&l->c[1]=='-'){while(l->c<l->e&&*l->c!='\n')av(l);}else break;}}
static Tn mt(Tk t,L lc,S lt){return(Tn){t,lc,lt,0,0.0};}
static Tn si_(Lx*l){L lc={l->ln,l->cl,l->f};const char*s=l->c;while(isalnum(pk(l))||pk(l)=='_')av(l);S lt={s,l->c-s};Tk t=kl(lt);if(t==T_ID){for(int j=0;KW[j].k.s;j++){if(lt.n>KW[j].k.n&&!memcmp(s,KW[j].k.s,KW[j].k.n)){char c=s[KW[j].k.n];if((isupper(KW[j].k.s[0])&&isupper(c))||(islower(KW[j].k.s[0])&&islower(c)))return mt(T_ERR,lc,Z("kw+id"));}}return mt(t,lc,lt);}if(t!=T_ID&&l->c<l->e&&(isalnum(*l->c)||*l->c=='_'))return mt(T_ERR,lc,Z("kw+x"));return mt(t,lc,lt);}
static Tn sn(Lx*l){L lc={l->ln,l->cl,l->f};const char*s=l->c;const char*ms=0,*me=0,*es=0;int b=10;bool ir=false,bx=false;char bd=0;while(isdigit(pk(l))||pk(l)=='_')av(l);if(pk(l)=='#'||(pk(l)==':'&&isxdigit(p2(l)))){bd=pk(l);const char*be=l->c;av(l);char*bp=al(32);int bi=0;for(const char*p=s;p<be;p++)if(*p!='_')bp[bi++]=*p;bp[bi]=0;b=atoi(bp);ms=l->c;while(isxdigit(pk(l))||pk(l)=='_')av(l);if(pk(l)=='.'){ir=true;av(l);while(isxdigit(pk(l))||pk(l)=='_')av(l);}if(pk(l)==bd){me=l->c;av(l);}if(tolower(pk(l))=='e'){bx=true;av(l);if(pk(l)=='+'||pk(l)=='-')av(l);es=l->c;while(isdigit(pk(l))||pk(l)=='_')av(l);}}else{if(pk(l)=='.'){if(p2(l)!='.'&&!isalpha(p2(l))){ir=true;av(l);while(isdigit(pk(l))||pk(l)=='_')av(l);}}if(tolower(pk(l))=='e'){ir=true;av(l);if(pk(l)=='+'||pk(l)=='-')av(l);while(isdigit(pk(l))||pk(l)=='_')av(l);}}if(isalpha(pk(l)))return mt(T_ERR,lc,Z("num+alpha"));Tn tk=mt(bx?(ir?T_REAL:T_INT):(ir?T_REAL:T_INT),lc,(S){s,l->c-s});if(bx&&es){char*mp=al(512);char*ep=al(512);int mi=0,ei=0;for(const char*p=ms;p<me;p++)if(*p!='_'&&*p!=bd)mp[mi++]=*p;mp[mi]=0;for(const char*p=es;p<l->c;p++)if(*p!='_')ep[ei++]=*p;ep[ei]=0;double m=0;int dp=-1;for(int i=0;i<mi;i++){if(mp[i]=='.'){dp=i;break;}}for(int i=0;i<mi;i++){if(mp[i]=='.')continue;int dv=mp[i]>='A'?mp[i]-'A'+10:mp[i]>='a'?mp[i]-'a'+10:mp[i]-'0';if(dp<0||i<dp)m=m*b+dv;else m+=dv/pow(b,i-dp);}int ex=atoi(ep);double rv=m*pow(b,ex);if(ir)tk.fv=rv;else tk.iv=(int64_t)rv;}else{char*tp=al(512);int j=0;const char*start=(bd&&ms)?ms:s;const char*end=(bd&&me)?me:l->c;for(const char*p=start;p<end;p++)if(*p!='_'&&*p!='#'&&*p!=':')tp[j++]=*p;tp[j]=0;if(ir)tk.fv=strtod(tp,0);else tk.iv=strtoll(tp,0,b);}return tk;}
static Tn sc(Lx*l){L lc={l->ln,l->cl,l->f};av(l);if(pk(l)==0)return mt(T_ERR,lc,Z("uc"));char c=pk(l);av(l);if(pk(l)!='\'')return mt(T_ERR,lc,Z("uc"));av(l);Tn tk=mt(T_CHAR,lc,(S){&c,1});tk.iv=c;return tk;}
static Tn ss(Lx*l){L lc={l->ln,l->cl,l->f};char d=pk(l);av(l);const char*s=l->c;char*b=al(256),*p=b;int n=0;while(pk(l)){if(pk(l)==d){if(p2(l)==d){av(l);av(l);if(n<255)*p++=d;n++;}else break;}else{if(n<255)*p++=pk(l);n++;av(l);}}if(pk(l)==d)av(l);else return mt(T_ERR,lc,Z("us"));*p=0;S lt={b,n};return mt(T_STR,lc,lt);}
static Tn lnx(Lx*l){sw(l);L lc={l->ln,l->cl,l->f};char c=pk(l);if(!c)return mt(T_EOF,lc,N);if(isalpha(c))return si_(l);if(isdigit(c))return sn(l);if(c=='\''){char c2=p2(l);if(c2&&p3(l)=='\''&&(l->c+3>=l->e||l->c[3]!='\'')&&((c2!='('&&c2!=')')||(l->c+3>=l->e||!isalnum(l->c[3]))))return sc(l);av(l);return mt(T_TK,lc,Z("'"));}if(c=='"'||c=='%')return ss(l);av(l);switch(c){case'(':return mt(T_LP,lc,Z("("));case')':return mt(T_RP,lc,Z(")"));case'[':return mt(T_LB,lc,Z("["));case']':return mt(T_RB,lc,Z("]"));case',':return mt(T_CM,lc,Z(","));case';':return mt(T_SC,lc,Z(";"));case'&':return mt(T_AM,lc,Z("&"));case'|':return mt(T_BR,lc,Z("|"));case'+':return mt(T_PL,lc,Z("+"));case'-':return mt(T_MN,lc,Z("-"));case'/':if(pk(l)=='='){av(l);return mt(T_NE,lc,Z("/="));}return mt(T_SL,lc,Z("/"));case'*':if(pk(l)=='*'){av(l);return mt(T_EX,lc,Z("**"));}return mt(T_ST,lc,Z("*"));case'=':if(pk(l)=='>'){av(l);return mt(T_AR,lc,Z("=>"));}return mt(T_EQ,lc,Z("="));case':':if(pk(l)=='='){av(l);return mt(T_AS,lc,Z(":="));}return mt(T_CL,lc,Z(":"));case'.':if(pk(l)=='.'){av(l);return mt(T_DD,lc,Z(".."));}return mt(T_DT,lc,Z("."));case'<':if(pk(l)=='='){av(l);return mt(T_LE,lc,Z("<="));}if(pk(l)=='<'){av(l);return mt(T_LL,lc,Z("<<"));}if(pk(l)=='>'){av(l);return mt(T_BX,lc,Z("<>"));}return mt(T_LT,lc,Z("<"));case'>':if(pk(l)=='='){av(l);return mt(T_GE,lc,Z(">="));}if(pk(l)=='>'){av(l);return mt(T_GG,lc,Z(">>"));}return mt(T_GT,lc,Z(">"));}return mt(T_ERR,lc,Z("ux"));}
typedef enum{N_ERR=0,N_ID,N_INT,N_REAL,N_CHAR,N_STR,N_NULL,N_AG,N_BIN,N_UN,N_AT,N_QL,N_CL,N_IX,N_SL,N_SEL,N_ALC,N_TI,N_TE,N_TF,N_TX,N_TA,N_TR,N_TAC,N_TP,N_ST,N_RN,N_CN,N_CM,N_VR,N_VP,N_DS,N_PM,N_PS,N_FS,N_PB,N_FB,N_PD,N_FD,N_PKS,N_PKB,N_PKD,N_OD,N_ND,N_TD,N_SD,N_ED,N_RE,N_AS,N_IF,N_CS,N_LP,N_BL,N_EX,N_RT,N_GT,N_RS,N_NS,N_CLT,N_EC,N_DL,N_AB,N_CD,N_ACC,N_SLS,N_SA,N_TKS,N_TKB,N_TKD,N_ENT,N_EI,N_HD,N_CH,N_ASC,N_WH,N_EL,N_WI,N_US,N_PG,N_RP,N_GD,N_GI,N_GF,N_CU,N_CX,N_LST,N_DRF,N_CVT,N_CHK,N_RRC,N_ERC,N_LNC,N_ADC,N_ALC2,N_DRV,N_LBL,N_OPID,N_GTP,N_GVL,N_GSP,N_GEN,N_GINST,N_TRM,N_CNT}Nk;
typedef struct Ty Ty;typedef struct No No;typedef struct Sy Sy;typedef struct RC RC;typedef struct LU LU;typedef struct GT GT;typedef struct{No**d;uint32_t n,c;}NV;typedef struct{Sy**d;uint32_t n,c;}SV;typedef struct{RC**d;uint32_t n,c;}RV;typedef struct{LU**d;uint32_t n,c;}LV;typedef struct{GT**d;uint32_t n,c;}GV;typedef struct{FILE**d;uint32_t n,c;}FV;typedef struct{S*d;uint32_t n,c;}SLV;
static void nv(NV*v,No*n){if(v->n>=v->c){v->c=v->c?v->c*2:8;v->d=realloc(v->d,v->c*sizeof(No*));}v->d[v->n++]=n;}
static void sv(SV*v,Sy*s){if(v->n>=v->c){v->c=v->c?v->c*2:8;v->d=realloc(v->d,v->c*sizeof(Sy*));}v->d[v->n++]=s;}
static void rv(RV*v,RC*r){if(v->n>=v->c){v->c=v->c?v->c*2:8;v->d=realloc(v->d,v->c*sizeof(RC*));}v->d[v->n++]=r;}
static void lv(LV*v,LU*l){if(v->n>=v->c){v->c=v->c?v->c*2:8;v->d=realloc(v->d,v->c*sizeof(LU*));}v->d[v->n++]=l;}
static void gv(GV*v,GT*g){if(v->n>=v->c){v->c=v->c?v->c*2:8;v->d=realloc(v->d,v->c*sizeof(GT*));}v->d[v->n++]=g;}
static void fv(FV*v,FILE*f){if(v->n>=v->c){v->c=v->c?v->c*2:8;v->d=realloc(v->d,v->c*sizeof(FILE*));}v->d[v->n++]=f;}
static void slv(SLV*v,S s){if(v->n>=v->c){v->c=v->c?v->c*2:8;v->d=realloc(v->d,v->c*sizeof(S));}v->d[v->n++]=s;}
struct No{Nk k;L l;Ty*ty;Sy*sy;union{S s;int64_t i;double f;struct{Tk op;No*l,*r;}bn;struct{Tk op;No*x;}un;struct{No*p;S at;NV ar;}at;struct{No*nm,*ag;}ql;struct{No*fn;NV ar;}cl;struct{No*p;NV ix;}ix;struct{No*p;No*lo,*hi;}sl;struct{No*p;S se;}se;struct{No*st;No*in;}alc;struct{No*lo,*hi;}rn;struct{No*rn;NV cs;}cn;struct{S nm;No*ty;No*in;bool al;uint32_t of,bt;No*dc;No*dsc;}cm;struct{NV ch;NV cmm;}vr;struct{No*ds;NV vrr;uint32_t sz;}vp;struct{S nm;No*ty;No*df;uint8_t md;}pm;struct{S nm;NV pmm;No*rt;S op;}sp;struct{No*sp;NV dc;NV st;NV hdd;int el;Sy*pr;NV lk;}bd;struct{S nm;NV dc;NV pr;int el;}ps;struct{S nm;NV dc;NV st;NV hddd;int el;}pb;struct{NV id;No*ty;No*in;bool co;}od;struct{S nm;No*df;No*ds;bool nw;bool drv;No*prt;NV dsc;}td;struct{S nm;No*in;No*cn;No*rn;}sd;struct{NV id;}ed;struct{S nm;No*rn;}re;struct{No*tg;No*vl;}as;struct{No*cd;NV th;NV ei;NV el;}if_;struct{No*ex;NV al;}cs;struct{S lb;No*it;bool rv;NV st;NV lk;}lp;struct{S lb;NV dc;NV st;NV hd;}bk;struct{S lb;No*cd;}ex;struct{No*vl;}rt;struct{S lb;}go;struct{No*ec;}rs;struct{No*nm;NV arr;}ct;struct{S nm;NV ixx;NV pmx;NV stx;NV hdx;No*gd;}acc;struct{NV al;NV el;}ss;struct{uint8_t kn;No*gd;NV sts;}sa;struct{S nm;NV en;bool it;}ts;struct{S nm;NV dc;NV st;NV hdz;}tb;struct{S nm;NV ixy;NV pmy;No*gd;}ent;struct{NV ec;NV stz;}hnd;struct{NV it;}ch;struct{NV ch;No*vl;}asc;struct{NV it;}lst;struct{NV wt;NV us;}cx;struct{S nm;}wt;struct{No*nm;}us;struct{S nm;NV ar;}pg;struct{No*cx;NV un;}cu;struct{No*x;}drf;struct{No*ty,*ex;}cvt;struct{No*ex;S ec;}chk;struct{No*bs;NV ops;}drv;struct{NV fp;NV dc;No*un;}gen;struct{S gn;NV ap;}gi;struct{NV it;No*lo,*hi;uint8_t dim;}ag;};};
struct RC{uint8_t k;Ty*ty;union{struct{S nm;uint32_t po;}er;struct{S nm;uint64_t ad;}ad;struct{S nm;NV cp;}rr;struct{S lang;S nm;S ext;}im;};};
struct LU{uint8_t k;S nm;S pth;No*sp;No*bd;LV wth;LV elb;uint64_t ts;bool cmpl;};
struct GT{S nm;NV fp;NV dc;No*un;};
static No*nd(Nk k,L l){No*n=al(sizeof(No));n->k=k;n->l=l;return n;}
static RC*rc(uint8_t k,Ty*t){RC*r=al(sizeof(RC));r->k=k;r->ty=t;return r;}
static LU*lu(uint8_t k,S nm,S pth){LU*l=al(sizeof(LU));l->k=k;l->nm=nm;l->pth=pth;return l;}
