static GT*gt(S nm){GT*g=al(sizeof(GT));g->nm=nm;return g;}
#define ND(k,l)nd(N_##k,l)
typedef struct{Lx lx;Tn cr,pk;int er;SLV lb;}Ps;
static void pn(Ps*p){p->cr=p->pk;p->pk=lnx(&p->lx);if(p->cr.t==T_AND&&p->pk.t==T_THEN){p->cr.t=T_ATHN;p->pk=lnx(&p->lx);}if(p->cr.t==T_OR&&p->pk.t==T_ELSE){p->cr.t=T_OREL;p->pk=lnx(&p->lx);}}
static bool pa(Ps*p,Tk t){return p->cr.t==t;}
static bool pm(Ps*p,Tk t){if(pa(p,t)){pn(p);return 1;}return 0;}
static void pe(Ps*p,Tk t){if(!pm(p,t))die(p->cr.l,"exp '%s' got '%s'",TN[t],TN[p->cr.t]);}
static L pl(Ps*p){return p->cr.l;}
static S pi(Ps*p){S s=p->cr.lit;pe(p,T_ID);return s;}
static S pat(Ps*p){S s;if(pa(p,T_ID))s=pi(p);else if(pa(p,T_RNG)){s=Z("RANGE");pn(p);}else if(pa(p,T_ACCS)){s=Z("ACCESS");pn(p);}else if(pa(p,T_DIG)){s=Z("DIGITS");pn(p);}else if(pa(p,T_DELTA)){s=Z("DELTA");pn(p);}else if(pa(p,T_MOD)){s=Z("MOD");pn(p);}else if(pa(p,T_REM)){s=Z("REM");pn(p);}else if(pa(p,T_ABS)){s=Z("ABS");pn(p);}else if(pa(p,T_NOT)){s=Z("NOT");pn(p);}else if(pa(p,T_AND)){s=Z("AND");pn(p);}else if(pa(p,T_OR)){s=Z("OR");pn(p);}else if(pa(p,T_XOR)){s=Z("XOR");pn(p);}else if(pa(p,T_PL)){s=Z("+");pn(p);}else if(pa(p,T_MN)){s=Z("-");pn(p);}else if(pa(p,T_ST)){s=Z("*");pn(p);}else if(pa(p,T_SL)){s=Z("/");pn(p);}else if(pa(p,T_EQ)){s=Z("=");pn(p);}else if(pa(p,T_NE)){s=Z("/=");pn(p);}else if(pa(p,T_LT)){s=Z("<");pn(p);}else if(pa(p,T_LE)){s=Z("<=");pn(p);}else if(pa(p,T_GT)){s=Z(">");pn(p);}else if(pa(p,T_GE)){s=Z(">=");pn(p);}else if(pa(p,T_AM)){s=Z("&");pn(p);}else if(pa(p,T_EX)){s=Z("**");pn(p);}else die(pl(p),"exp attr");return s;}
static No*pnm(Ps*p);static No*pex(Ps*p);static No*ppr(Ps*p);static No*prn(Ps*p);static NV pst(Ps*p);static NV pdc(Ps*p);static NV phd(Ps*p);static No*ps(Ps*p);static No*pgf(Ps*p);static RC*prc(Ps*p);
static No*ppr(Ps*p){L lc=pl(p);if(pm(p,T_LP)){NV v={0};do{NV ch={0};No*e=pex(p);nv(&ch,e);while(pm(p,T_BR))nv(&ch,pex(p));if(pa(p,T_AR)){pn(p);No*vl=pex(p);for(uint32_t i=0;i<ch.n;i++){No*a=ND(ASC,lc);nv(&a->asc.ch,ch.d[i]);a->asc.vl=vl;nv(&v,a);}}else{if(ch.n==1)nv(&v,ch.d[0]);else die(lc,"exp '=>'");}}while(pm(p,T_CM));pe(p,T_RP);if(v.n==1&&v.d[0]->k!=N_ASC)return v.d[0];No*n=ND(AG,lc);n->ag.it=v;return n;}if(pm(p,T_NEW)){No*n=ND(ALC,lc);n->alc.st=pnm(p);if(pm(p,T_TK)){pe(p,T_LP);n->alc.in=pex(p);pe(p,T_RP);}return n;}if(pm(p,T_NULL))return ND(NULL,lc);if(pm(p,T_OTH)){No*n=ND(ID,lc);n->s=Z("others");return n;}if(pa(p,T_INT)){No*n=ND(INT,lc);n->i=p->cr.iv;pn(p);return n;}if(pa(p,T_REAL)){No*n=ND(REAL,lc);n->f=p->cr.fv;pn(p);return n;}if(pa(p,T_CHAR)){No*n=ND(CHAR,lc);n->i=p->cr.iv;pn(p);return n;}if(pa(p,T_STR)){No*n=ND(STR,lc);n->s=sd(p->cr.lit);pn(p);for(;;){if(pa(p,T_LP)){pn(p);NV v={0};do{NV ch={0};No*e=pex(p);if(e->k==N_ID&&pa(p,T_AR)){pn(p);No*a=ND(ASC,lc);nv(&a->asc.ch,e);a->asc.vl=pex(p);nv(&v,a);}else{nv(&ch,e);while(pm(p,T_BR))nv(&ch,pex(p));if(pa(p,T_AR)){pn(p);No*vl=pex(p);for(uint32_t i=0;i<ch.n;i++){No*a=ND(ASC,lc);nv(&a->asc.ch,ch.d[i]);a->asc.vl=vl;nv(&v,a);}}else{if(ch.n==1)nv(&v,ch.d[0]);else die(lc,"exp '=>'");}}}while(pm(p,T_CM));pe(p,T_RP);No*m=ND(CL,lc);m->cl.fn=n;m->cl.ar=v;n=m;}else break;}return n;}if(pa(p,T_ID))return pnm(p);if(pm(p,T_NOT)){No*n=ND(UN,lc);n->un.op=T_NOT;n->un.x=ppr(p);return n;}if(pm(p,T_ABS)){No*n=ND(UN,lc);n->un.op=T_ABS;n->un.x=ppr(p);return n;}if(pm(p,T_ALL)){No*n=ND(DRF,lc);n->drf.x=ppr(p);return n;}die(lc,"exp expr");}
static No*pnm(Ps*p){L lc=pl(p);No*n=ND(ID,lc);n->s=pi(p);for(;;){if(pm(p,T_DT)){if(pm(p,T_ALL)){No*m=ND(DRF,lc);m->drf.x=n;n=m;}else{No*m=ND(SEL,lc);m->se.p=n;if(pa(p,T_STR)){m->se.se=p->cr.lit;pn(p);}else m->se.se=pi(p);n=m;}}else if(pm(p,T_TK)){if(pa(p,T_LP)){pn(p);No*m=ND(QL,lc);m->ql.nm=n;NV v={0};do{NV ch={0};No*e=pex(p);nv(&ch,e);while(pm(p,T_BR))nv(&ch,pex(p));if(pa(p,T_AR)){pn(p);No*vl=pex(p);for(uint32_t i=0;i<ch.n;i++){No*a=ND(ASC,lc);nv(&a->asc.ch,ch.d[i]);a->asc.vl=vl;nv(&v,a);}}else{if(ch.n==1)nv(&v,ch.d[0]);else die(lc,"exp '=>'");}}while(pm(p,T_CM));pe(p,T_RP);if(v.n==1&&v.d[0]->k!=N_ASC)m->ql.ag=v.d[0];else{No*ag=ND(AG,lc);ag->ag.it=v;m->ql.ag=ag;}n=m;}else{S at=pat(p);No*m=ND(AT,lc);m->at.p=n;m->at.at=at;if(pm(p,T_LP)){do nv(&m->at.ar,pex(p));while(pm(p,T_CM));pe(p,T_RP);}n=m;}}else if(pa(p,T_LP)){pn(p);if(pa(p,T_RP)){pe(p,T_RP);No*m=ND(CL,lc);m->cl.fn=n;n=m;}else{NV v={0};do{NV ch={0};No*e=pex(p);if(e->k==N_ID&&pa(p,T_AR)){pn(p);No*a=ND(ASC,lc);nv(&a->asc.ch,e);a->asc.vl=pex(p);nv(&v,a);}else{nv(&ch,e);while(pm(p,T_BR))nv(&ch,pex(p));if(pa(p,T_AR)){pn(p);No*vl=pex(p);for(uint32_t i=0;i<ch.n;i++){No*a=ND(ASC,lc);nv(&a->asc.ch,ch.d[i]);a->asc.vl=vl;nv(&v,a);}}else{if(ch.n==1)nv(&v,ch.d[0]);else die(lc,"exp '=>'");}}}while(pm(p,T_CM));pe(p,T_RP);No*m=ND(CL,lc);m->cl.fn=n;m->cl.ar=v;n=m;}}else break;}return n;}
static No*ppw(Ps*p){No*n=ppr(p);if(pm(p,T_EX)){L lc=pl(p);No*m=ND(BIN,lc);m->bn.op=T_EX;m->bn.l=n;m->bn.r=ppw(p);return m;}return n;}
static No*pt(Ps*p){No*n=ppw(p);while(pa(p,T_ST)||pa(p,T_SL)||pa(p,T_MOD)||pa(p,T_REM)){Tk op=p->cr.t;pn(p);L lc=pl(p);No*m=ND(BIN,lc);m->bn.op=op;m->bn.l=n;m->bn.r=ppw(p);n=m;}return n;}
static No*psm(Ps*p){L lc=pl(p);Tk un=0;if(pm(p,T_MN))un=T_MN;else if(pm(p,T_PL))un=T_PL;No*n=pt(p);if(un){No*m=ND(UN,lc);m->un.op=un;m->un.x=n;n=m;}while(pa(p,T_PL)||pa(p,T_MN)||pa(p,T_AM)){Tk op=p->cr.t;pn(p);lc=pl(p);No*m=ND(BIN,lc);m->bn.op=op;m->bn.l=n;m->bn.r=pt(p);n=m;}return n;}
static No*prl(Ps*p){No*n=psm(p);if(pm(p,T_DD)){L lc=pl(p);No*m=ND(RN,lc);m->rn.lo=n;m->rn.hi=psm(p);return m;}if(pa(p,T_EQ)||pa(p,T_NE)||pa(p,T_LT)||pa(p,T_LE)||pa(p,T_GT)||pa(p,T_GE)||pa(p,T_IN)||pa(p,T_NOT)){Tk op=p->cr.t;pn(p);if(op==T_NOT)pe(p,T_IN);L lc=pl(p);No*m=ND(BIN,lc);m->bn.op=op;m->bn.l=n;if(op==T_IN||op==T_NOT)m->bn.r=prn(p);else m->bn.r=psm(p);return m;}return n;}
static No*pan(Ps*p){No*n=prl(p);while(pa(p,T_AND)||pa(p,T_ATHN)){Tk op=p->cr.t;pn(p);L lc=pl(p);No*m=ND(BIN,lc);m->bn.op=op;m->bn.l=n;m->bn.r=prl(p);n=m;}return n;}
static No*por(Ps*p){No*n=pan(p);while(pa(p,T_OR)||pa(p,T_OREL)||pa(p,T_XOR)){Tk op=p->cr.t;pn(p);L lc=pl(p);No*m=ND(BIN,lc);m->bn.op=op;m->bn.l=n;m->bn.r=pan(p);n=m;}return n;}
static No*pex(Ps*p){return por(p);}
static No*prn(Ps*p){L lc=pl(p);if(pm(p,T_BX)){No*n=ND(RN,lc);n->rn.lo=0;n->rn.hi=0;return n;}No*lo=psm(p);if(pm(p,T_DD)){No*m=ND(RN,lc);m->rn.lo=lo;m->rn.hi=psm(p);return m;}return lo;}
static No*psi(Ps*p){L lc=pl(p);No*n=ND(ID,lc);n->s=pi(p);for(;;){if(pm(p,T_DT)){if(pm(p,T_ALL)){No*m=ND(DRF,lc);m->drf.x=n;n=m;}else{No*m=ND(SEL,lc);m->se.p=n;m->se.se=pi(p);n=m;}}else if(pm(p,T_TK)){S at=pat(p);No*m=ND(AT,lc);m->at.p=n;m->at.at=at;if(pm(p,T_LP)){do nv(&m->at.ar,pex(p));while(pm(p,T_CM));pe(p,T_RP);}n=m;}else break;}if(pm(p,T_DELTA)){psm(p);}if(pm(p,T_DIG)){pex(p);}if(pm(p,T_RNG)){L lc=pl(p);No*c=ND(CN,lc);c->cn.rn=prn(p);No*m=ND(ST,lc);m->sd.in=n;m->sd.cn=c;return m;}if(pa(p,T_LP)){pn(p);L lc=pl(p);No*c=ND(CN,lc);do{L lc2=pl(p);No*r=prn(p);if(r->k==N_ID&&pm(p,T_RNG)){No*tn=ND(ID,lc2);tn->s=r->s;No*rng=prn(p);No*si=ND(ST,lc2);No*cn=ND(CN,lc2);cn->cn.rn=rng;si->sd.in=tn;si->sd.cn=cn;nv(&c->cn.cs,si);}else if(r->k==N_ID&&pm(p,T_AR)){No*a=ND(ASC,lc2);nv(&a->asc.ch,r);a->asc.vl=pex(p);nv(&c->cn.cs,a);}else{nv(&c->cn.cs,r);}}while(pm(p,T_CM));pe(p,T_RP);No*m=ND(ST,lc);m->sd.in=n;m->sd.cn=c;return m;}return n;}
static NV ppm(Ps*p){NV v={0};if(!pm(p,T_LP))return v;do{L lc=pl(p);NV id={0};do{S nm=pi(p);No*i=ND(ID,lc);i->s=nm;nv(&id,i);}while(pm(p,T_CM));pe(p,T_CL);uint8_t md=0;if(pm(p,T_IN))md|=1;if(pm(p,T_OUT))md|=2;if(!md)md=1;No*ty=pnm(p);No*df=0;if(pm(p,T_AS))df=pex(p);for(uint32_t i=0;i<id.n;i++){No*n=ND(PM,lc);n->pm.nm=id.d[i]->s;n->pm.ty=ty;n->pm.df=df;n->pm.md=md;nv(&v,n);}}while(pm(p,T_SC));pe(p,T_RP);return v;}
static No*pps_(Ps*p){L lc=pl(p);pe(p,T_PROC);No*n=ND(PS,lc);if(pa(p,T_STR)){n->sp.nm=p->cr.lit;pn(p);}else n->sp.nm=pi(p);n->sp.pmm=ppm(p);return n;}
static No*pfs(Ps*p){L lc=pl(p);pe(p,T_FUN);No*n=ND(FS,lc);if(pa(p,T_STR)){n->sp.nm=p->cr.lit;pn(p);}else n->sp.nm=pi(p);n->sp.pmm=ppm(p);pe(p,T_RET);n->sp.rt=pnm(p);return n;}
static No*ptd(Ps*p);
static NV pgfp(Ps*p){NV v={0};while(!pa(p,T_PROC)&&!pa(p,T_FUN)&&!pa(p,T_PKG)){if(pm(p,T_TYP)){L lc=pl(p);S nm=pi(p);bool isp=false;if(pm(p,T_LP)){while(!pa(p,T_RP))pn(p);pe(p,T_RP);}if(pm(p,T_IS)){if(pm(p,T_DIG)||pm(p,T_DELTA)||pm(p,T_RNG)){pe(p,T_BX);}else if(pm(p,T_LP)){pe(p,T_BX);pe(p,T_RP);isp=true;}else if(pm(p,T_LIM)||pa(p,T_ARR)||pa(p,T_REC)||pa(p,T_ACCS)||pa(p,T_PRV)){ptd(p);}else pex(p);}No*n=ND(GTP,lc);n->td.nm=nm;nv(&v,n);pe(p,T_SC);}else if(pm(p,T_WITH)){if(pa(p,T_PROC)){No*sp=pps_(p);sp->k=N_GSP;if(pm(p,T_IS)){if(!pm(p,T_BX)){while(!pa(p,T_SC))pn(p);}}nv(&v,sp);}else if(pa(p,T_FUN)){No*sp=pfs(p);sp->k=N_GSP;if(pm(p,T_IS)){if(!pm(p,T_BX)){while(!pa(p,T_SC))pn(p);}}nv(&v,sp);}else{L lc=pl(p);NV id={0};do{S nm=pi(p);No*i=ND(ID,lc);i->s=nm;nv(&id,i);}while(pm(p,T_CM));pe(p,T_CL);uint8_t md=0;if(pm(p,T_IN))md|=1;if(pm(p,T_OUT))md|=2;if(!md)md=1;No*ty=pnm(p);pm(p,T_AS);if(!pa(p,T_SC))pex(p);No*n=ND(GVL,lc);n->od.id=id;n->od.ty=ty;nv(&v,n);}pe(p,T_SC);}else{L lc=pl(p);NV id={0};do{S nm=pi(p);No*i=ND(ID,lc);i->s=nm;nv(&id,i);}while(pm(p,T_CM));pe(p,T_CL);uint8_t md=0;if(pm(p,T_IN))md|=1;if(pm(p,T_OUT))md|=2;if(!md)md=1;No*ty=pnm(p);pm(p,T_AS);if(!pa(p,T_SC))pex(p);No*n=ND(GVL,lc);n->od.id=id;n->od.ty=ty;nv(&v,n);pe(p,T_SC);}}return v;}
static No*pgf(Ps*p){L lc=pl(p);pe(p,T_GEN);No*n=ND(GEN,lc);n->gen.fp=pgfp(p);if(pa(p,T_PROC)){No*sp=pps_(p);pe(p,T_SC);n->gen.un=ND(PD,lc);n->gen.un->bd.sp=sp;return n;}if(pa(p,T_FUN)){No*sp=pfs(p);pe(p,T_SC);n->gen.un=ND(FD,lc);n->gen.un->bd.sp=sp;return n;}if(pm(p,T_PKG)){S nm=pi(p);pe(p,T_IS);NV dc=pdc(p);if(pm(p,T_PRV)){NV pr=pdc(p);for(uint32_t i=0;i<pr.n;i++)nv(&dc,pr.d[i]);}n->gen.dc=dc;pe(p,T_END);if(pa(p,T_ID))pn(p);pe(p,T_SC);No*pk=ND(PKS,lc);pk->ps.nm=nm;pk->ps.dc=n->gen.dc;n->gen.un=pk;return n;}return n;}
static No*pif(Ps*p){L lc=pl(p);pe(p,T_IF);No*n=ND(IF,lc);n->if_.cd=pex(p);pe(p,T_THEN);while(!pa(p,T_ELSIF)&&!pa(p,T_ELSE)&&!pa(p,T_END))nv(&n->if_.th,ps(p));while(pm(p,T_ELSIF)){No*e=ND(EL,lc);e->if_.cd=pex(p);pe(p,T_THEN);while(!pa(p,T_ELSIF)&&!pa(p,T_ELSE)&&!pa(p,T_END))nv(&e->if_.th,ps(p));nv(&n->if_.ei,e);}if(pm(p,T_ELSE))while(!pa(p,T_END))nv(&n->if_.el,ps(p));pe(p,T_END);pe(p,T_IF);pe(p,T_SC);return n;}
static No*pcs(Ps*p){L lc=pl(p);pe(p,T_CSE);No*n=ND(CS,lc);n->cs.ex=pex(p);pe(p,T_IS);while(pa(p,T_PGM))prc(p);while(pm(p,T_WHN)){No*a=ND(WH,lc);do{No*e=pex(p);if(e->k==N_ID&&pm(p,T_RNG)){No*r=prn(p);nv(&a->ch.it,r);}else if(pm(p,T_DD)){No*r=ND(RN,lc);r->rn.lo=e;r->rn.hi=pex(p);nv(&a->ch.it,r);}else nv(&a->ch.it,e);}while(pm(p,T_BR));pe(p,T_AR);while(!pa(p,T_WHN)&&!pa(p,T_END))nv(&a->hnd.stz,ps(p));nv(&n->cs.al,a);}pe(p,T_END);pe(p,T_CSE);pe(p,T_SC);return n;}
