PACKAGE BODY MATH IS
FUNCTION ADD(A,B:INTEGER)RETURN INTEGER IS
BEGIN
RETURN A+B;
END ADD;
FUNCTION MUL(A,B:INTEGER)RETURN INTEGER IS
BEGIN
RETURN A*B;
END MUL;
PROCEDURE CALC(X:INTEGER;Y:OUT INTEGER)IS
BEGIN
Y:=ADD(MUL(X,2),3);
END CALC;
END MATH;
