WITH TEXT_IO;USE TEXT_IO;
PACKAGE TEST_EX IS
MY_ERROR:EXCEPTION;
ANOTHER_ERROR:EXCEPTION;
PROCEDURE RAISE_TEST;
END TEST_EX;
PACKAGE BODY TEST_EX IS
PROCEDURE RAISE_TEST IS
BEGIN
RAISE MY_ERROR;
EXCEPTION
WHEN MY_ERROR=>PUT_LINE("caught");
WHEN OTHERS=>PUT_LINE("other");
END RAISE_TEST;
END TEST_EX;
WITH TEST_EX;USE TEST_EX;
PROCEDURE MAIN IS
BEGIN
RAISE_TEST;
RAISE ANOTHER_ERROR;
EXCEPTION
WHEN ANOTHER_ERROR=>NULL;
END MAIN;
