PROCEDURE TEST_PRAGMA_OUT IS
  PROCEDURE EXTERNAL_PROC(S: OUT STRING; N: OUT INTEGER);
  PRAGMA IMPORT(LLVM, EXTERNAL_PROC, "__external_out");
  BUF: STRING(1..10);
  LEN: INTEGER;
BEGIN
  EXTERNAL_PROC(BUF, LEN);
END TEST_PRAGMA_OUT;
