PACKAGE MATH_PKG IS
DIV_ERROR:EXCEPTION;
OVERFLOW:EXCEPTION;
FUNCTION DIVIDE(A,B:INTEGER)RETURN INTEGER;
END MATH_PKG;
PACKAGE BODY MATH_PKG IS
FUNCTION DIVIDE(A,B:INTEGER)RETURN INTEGER IS
BEGIN
IF B=0 THEN RAISE DIV_ERROR;END IF;
RETURN A/B;
EXCEPTION
WHEN DIV_ERROR=>RAISE;
WHEN CONSTRAINT_ERROR=>RAISE OVERFLOW;
END DIVIDE;
END MATH_PKG;
WITH MATH_PKG;USE MATH_PKG;
WITH TEXT_IO;USE TEXT_IO;
PROCEDURE TEST_COMPREHENSIVE IS
R:INTEGER;
BEGIN
R:=DIVIDE(10,2);
R:=DIVIDE(10,0);
EXCEPTION
WHEN DIV_ERROR=>PUT_LINE("div");
WHEN OVERFLOW=>PUT_LINE("ovf");
WHEN OTHERS=>PUT_LINE("oth");
END TEST_COMPREHENSIVE;
