WITH REPORT; USE REPORT;

PROCEDURE TEST_MEMBERSHIP IS
  SUBTYPE ST IS INTEGER RANGE -10 .. 10;
  I1 : INTEGER := IDENT_INT(1);
BEGIN
  TEST("TEST_MEMBERSHIP", "Test membership with subtype");

  IF I1 IN ST THEN
    NULL;
  ELSE
    FAILED("I1 should be in ST");
  END IF;

  RESULT;
END TEST_MEMBERSHIP;
