WITH TEXT_IO; USE TEXT_IO;
WITH UNCHECKED_CONVERSION;
PROCEDURE PACKED_DYNAMIC IS
     FUNCTION IDENT (X : INTEGER) RETURN INTEGER IS
     BEGIN RETURN X; END IDENT;
     LEN : CONSTANT INTEGER := IDENT (7);
     TYPE BITS IS ARRAY (1 .. LEN) OF BOOLEAN;
     PRAGMA PACK (BITS);
     TYPE ROWS IS ARRAY (1 .. 3) OF BITS;
     TYPE BYTE IS RANGE -128 .. 127;
     FUNCTION TO_BITS IS NEW UNCHECKED_CONVERSION (BYTE, BITS);
     FUNCTION FROM_BITS IS NEW UNCHECKED_CONVERSION (BITS, BYTE);
     B : BITS := (OTHERS => FALSE);
     R : ROWS := (OTHERS => (OTHERS => FALSE));
     V : BYTE := 45;
BEGIN
     B := TO_BITS (V);
     FOR I IN 1 .. LEN LOOP
          R (IDENT (1)) (IDENT (I)) := B (I);
     END LOOP;
     IF V /= FROM_BITS (R (1)) THEN PUT_LINE ("FAIL ROUNDTRIP"); END IF;
     IF B (1) /= TRUE OR B (2) /= FALSE OR B (3) /= TRUE THEN
          PUT_LINE ("FAIL BITS");
     END IF;
     PUT_LINE ("DONE");
END PACKED_DYNAMIC;
