WITH TEXT_IO; USE TEXT_IO;
WITH UNCHECKED_CONVERSION;
PROCEDURE PACKED_GENERIC_ROUNDTRIP IS
     SUBTYPE SUBINTEGER IS INTEGER RANGE -1 .. 1;
     CHECK_SIZE : CONSTANT INTEGER := INTEGER'SIZE/2;
     TYPE REC IS RECORD
          RECVAR : SUBINTEGER;
     END RECORD;
     FOR REC USE RECORD
          RECVAR AT 0 RANGE 0 .. CHECK_SIZE-1;
     END RECORD;
     REC1 : REC := (RECVAR => 1);

     GENERIC
        TYPE TEST_TYPE IS PRIVATE;
     PROCEDURE LC (TEST_VALUE : TEST_TYPE; EXPECTED_LENGTH : INTEGER);

     PROCEDURE LC (TEST_VALUE : TEST_TYPE; EXPECTED_LENGTH : INTEGER) IS
        FUNCTION IDENT (X : INTEGER) RETURN INTEGER IS BEGIN RETURN X; END IDENT;
        LEN : CONSTANT INTEGER := EXPECTED_LENGTH;
        TYPE BIT_ARRAY_TYPE IS ARRAY (1 .. LEN) OF BOOLEAN;
        PRAGMA PACK (BIT_ARRAY_TYPE);
        TYPE NEW_BIT_ARRAY_TYPE IS ARRAY (1 .. 3) OF BIT_ARRAY_TYPE;
        FUNCTION TO_BITS IS NEW UNCHECKED_CONVERSION (TEST_TYPE, BIT_ARRAY_TYPE);
        FUNCTION FROM_BITS IS NEW UNCHECKED_CONVERSION (BIT_ARRAY_TYPE, TEST_TYPE);
        BIT_ARRAY : BIT_ARRAY_TYPE := (OTHERS => FALSE);
        BIT_ARRAY_NEW : NEW_BIT_ARRAY_TYPE := (OTHERS => (OTHERS => FALSE));
     BEGIN
        BIT_ARRAY := TO_BITS (TEST_VALUE);
        FOR I IN 1 .. LEN LOOP
             BIT_ARRAY_NEW(IDENT(1)) (IDENT(I)) := BIT_ARRAY(I);
        END LOOP;
        IF NOT BIT_ARRAY_NEW (1) (1) THEN PUT_LINE ("FAIL NEW-BIT1"); END IF;
        IF BIT_ARRAY_NEW (1) (2) THEN PUT_LINE ("FAIL NEW-BIT2"); END IF;
        IF TEST_VALUE /= FROM_BITS (BIT_ARRAY_NEW(1)) THEN
           PUT_LINE ("FAIL ROUNDTRIP");
        END IF;
     END LC;

     PROCEDURE LEN_REC IS NEW LC (REC);
BEGIN
     LEN_REC (REC1, CHECK_SIZE-1);
     PUT_LINE ("DONE");
END PACKED_GENERIC_ROUNDTRIP;
