WITH TEXT_IO; USE TEXT_IO;
PROCEDURE PACKED_NESTED_ROWS IS
     FUNCTION IDENT (X : INTEGER) RETURN INTEGER IS BEGIN RETURN X; END IDENT;
     LEN : CONSTANT INTEGER := IDENT (7);
     TYPE BITS IS ARRAY (1 .. LEN) OF BOOLEAN;
     PRAGMA PACK (BITS);
     TYPE ROWS IS ARRAY (1 .. 3) OF BITS;
     R : ROWS := (OTHERS => (OTHERS => FALSE));
BEGIN
     R (IDENT (1)) (IDENT (3)) := TRUE;
     IF NOT R (1) (3)                   THEN PUT_LINE ("FAIL A"); END IF;
     IF NOT R (IDENT (1)) (IDENT (3))   THEN PUT_LINE ("FAIL B"); END IF;
     IF R (2) (3)                       THEN PUT_LINE ("FAIL C"); END IF;
     R (2) (IDENT (5)) := TRUE;
     IF NOT R (IDENT (2)) (5)           THEN PUT_LINE ("FAIL D"); END IF;
     PUT_LINE ("DONE");
END PACKED_NESTED_ROWS;
