WITH TEXT_IO; USE TEXT_IO;
WITH UNCHECKED_CONVERSION;
PROCEDURE PACKED_STATIC IS
     TYPE BOOL_ARR IS ARRAY (1..32) OF BOOLEAN;
     PRAGMA PACK (BOOL_ARR);
     FUNCTION INT_TO_BOOL IS NEW UNCHECKED_CONVERSION (INTEGER, BOOL_ARR);
     FUNCTION BOOL_TO_INT IS NEW UNCHECKED_CONVERSION (BOOL_ARR, INTEGER);
     I : INTEGER;
     B : BOOL_ARR;
BEGIN
     I := BOOL_TO_INT((1..32 => TRUE));
     IF I /= -1 THEN PUT_LINE ("FAIL1"); END IF;
     B := INT_TO_BOOL(I);
     IF B /= (1..32 => TRUE) THEN PUT_LINE ("FAIL2"); END IF;
     FOR J IN B'RANGE LOOP
       IF NOT B(J) THEN PUT_LINE ("FAIL3"); END IF;
     END LOOP;
     B(5) := FALSE;
     IF BOOL_TO_INT(B) /= -17 THEN PUT_LINE ("FAIL4"); END IF;
     PUT_LINE ("DONE");
END PACKED_STATIC;
