PACKAGE BODY CALENDAR IS
FUNCTION RT_TIME RETURN DURATION;
PRAGMA IMPORT(LLVM,RT_TIME,"__ada_clock");
EPOCH:CONSTANT:=2440588;
FUNCTION JULIAN_DAY(Y:YEAR_NUMBER;M:MONTH_NUMBER;D:DAY_NUMBER)RETURN INTEGER IS
A:INTEGER:=(14-M)/12;
YY:INTEGER:=Y+4800-A;
MM:INTEGER:=M+12*A-3;
BEGIN
RETURN D+(153*MM+2)/5+365*YY+YY/4-YY/100+YY/400-32045;
END JULIAN_DAY;
FUNCTION CLOCK RETURN TIME IS BEGIN RETURN TIME(RT_TIME);END CLOCK;
FUNCTION YEAR(DATE:TIME)RETURN YEAR_NUMBER IS
D:DURATION:=DURATION(DATE);
DAYS:INTEGER:=INTEGER(D/86400.0);
JD:INTEGER:=EPOCH+DAYS;
A:INTEGER:=JD+32044;
B:INTEGER:=(4*A+3)/146097;
C:INTEGER:=A-146097*B/4;
DD:INTEGER:=(4*C+3)/1461;
E:INTEGER:=C-1461*DD/4;
M:INTEGER:=(5*E+2)/153;
YY:INTEGER:=100*B+DD-4800+M/10;
BEGIN
IF YY<1901 THEN RETURN 1901;ELSIF YY>2099 THEN RETURN 2099;ELSE RETURN YEAR_NUMBER(YY);END IF;
END YEAR;
FUNCTION MONTH(DATE:TIME)RETURN MONTH_NUMBER IS
D:DURATION:=DURATION(DATE);
DAYS:INTEGER:=INTEGER(D/86400.0);
JD:INTEGER:=EPOCH+DAYS;
A:INTEGER:=JD+32044;
B:INTEGER:=(4*A+3)/146097;
C:INTEGER:=A-146097*B/4;
DD:INTEGER:=(4*C+3)/1461;
E:INTEGER:=C-1461*DD/4;
M:INTEGER:=(5*E+2)/153;
MM:INTEGER:=M+3-12*(M/10);
BEGIN
IF MM<1 THEN RETURN 1;ELSIF MM>12 THEN RETURN 12;ELSE RETURN MONTH_NUMBER(MM);END IF;
END MONTH;
FUNCTION DAY(DATE:TIME)RETURN DAY_NUMBER IS
D:DURATION:=DURATION(DATE);
DAYS:INTEGER:=INTEGER(D/86400.0);
JD:INTEGER:=EPOCH+DAYS;
A:INTEGER:=JD+32044;
B:INTEGER:=(4*A+3)/146097;
C:INTEGER:=A-146097*B/4;
DD:INTEGER:=(4*C+3)/1461;
E:INTEGER:=C-1461*DD/4;
M:INTEGER:=(5*E+2)/153;
DY:INTEGER:=E-(153*M+2)/5+1;
BEGIN
IF DY<1 THEN RETURN 1;ELSIF DY>31 THEN RETURN 31;ELSE RETURN DAY_NUMBER(DY);END IF;
END DAY;
FUNCTION SECONDS(DATE:TIME)RETURN DAY_DURATION IS
D:DURATION:=DURATION(DATE);
DAYS:INTEGER:=INTEGER(D/86400.0);
SECS:DURATION:=D-DURATION(DAYS)*86400.0;
BEGIN
IF SECS<0.0 THEN RETURN 0.0;ELSIF SECS>86400.0 THEN RETURN 86400.0;ELSE RETURN DAY_DURATION(SECS);END IF;
END SECONDS;
PROCEDURE SPLIT(DATE:IN TIME;YEAR:OUT YEAR_NUMBER;MONTH:OUT MONTH_NUMBER;DAY:OUT DAY_NUMBER;SECONDS:OUT DAY_DURATION)IS
BEGIN
YEAR:=CALENDAR.YEAR(DATE);
MONTH:=CALENDAR.MONTH(DATE);
DAY:=CALENDAR.DAY(DATE);
SECONDS:=CALENDAR.SECONDS(DATE);
END SPLIT;
FUNCTION TIME_OF(YEAR:YEAR_NUMBER;MONTH:MONTH_NUMBER;DAY:DAY_NUMBER;SECONDS:DAY_DURATION:=0.0)RETURN TIME IS
JD:INTEGER:=JULIAN_DAY(YEAR,MONTH,DAY);
DAYS:INTEGER:=JD-EPOCH;
D:DURATION:=DURATION(DAYS)*86400.0+SECONDS;
BEGIN
RETURN TIME(D);
END TIME_OF;
FUNCTION "+"(LEFT:TIME;RIGHT:DURATION)RETURN TIME IS BEGIN RETURN TIME(DURATION(LEFT)+RIGHT);END "+";
FUNCTION "+"(LEFT:DURATION;RIGHT:TIME)RETURN TIME IS BEGIN RETURN TIME(LEFT+DURATION(RIGHT));END "+";
FUNCTION "-"(LEFT:TIME;RIGHT:DURATION)RETURN TIME IS BEGIN RETURN TIME(DURATION(LEFT)-RIGHT);END "-";
FUNCTION "-"(LEFT:TIME;RIGHT:TIME)RETURN DURATION IS BEGIN RETURN DURATION(LEFT)-DURATION(RIGHT);END "-";
FUNCTION "<"(LEFT,RIGHT:TIME)RETURN BOOLEAN IS BEGIN RETURN DURATION(LEFT)<DURATION(RIGHT);END "<";
FUNCTION "<="(LEFT,RIGHT:TIME)RETURN BOOLEAN IS BEGIN RETURN DURATION(LEFT)<=DURATION(RIGHT);END "<=";
FUNCTION ">"(LEFT,RIGHT:TIME)RETURN BOOLEAN IS BEGIN RETURN DURATION(LEFT)>DURATION(RIGHT);END ">";
FUNCTION ">="(LEFT,RIGHT:TIME)RETURN BOOLEAN IS BEGIN RETURN DURATION(LEFT)>=DURATION(RIGHT);END ">=";
END CALENDAR;
