PACKAGE BODY CALENDAR IS

FUNCTION RT_TIME RETURN DURATION;
PRAGMA IMPORT(LLVM,RT_TIME,"__ada_clock");

-- Julian day number of the Unix epoch, 1970-01-01.
EPOCH:CONSTANT:=2440588;

-- A full day, as a named constant: a bare 86_400.0 next to "+" would be
-- capturable by the TIME operators (a universal literal converts to TIME).
DAY_SECONDS:CONSTANT DURATION:=86_400.0;

-- The representable range of TIME: from 1901-01-01 00:00:00 to
-- 2099-12-31 24:00:00 (SECONDS may be 86_400.0, RM 9.6). Assigned in the
-- initialization part below, after JULIAN_DAY's body has elaborated
-- (RM 3.9 puts every object declaration ahead of the bodies).
TIME_FIRST:DURATION;
TIME_LAST:DURATION;

FUNCTION JULIAN_DAY(Y:YEAR_NUMBER;M:MONTH_NUMBER;D:DAY_NUMBER)RETURN INTEGER IS
A:INTEGER:=(14-M)/12;
YY:INTEGER:=Y+4800-A;
MM:INTEGER:=M+12*A-3;
BEGIN
RETURN D+(153*MM+2)/5+365*YY+YY/4-YY/100+YY/400-32045;
END JULIAN_DAY;

-- Days since the Unix epoch of the day containing DATE, i.e. the floor of
-- DATE / 86_400.0. Integer conversion rounds to nearest (RM 4.6), so step
-- back while the resulting midnight lies after DATE.
FUNCTION DAY_COUNT(DATE:TIME)RETURN INTEGER IS
D:DURATION:=DURATION(DATE);
N:INTEGER:=INTEGER(D/DAY_SECONDS);
BEGIN
WHILE DURATION(N)*DAY_SECONDS>D LOOP N:=N-1;END LOOP;
RETURN N;
END DAY_COUNT;

FUNCTION CLOCK RETURN TIME IS BEGIN RETURN TIME(RT_TIME);END CLOCK;

PROCEDURE SPLIT(DATE:IN TIME;YEAR:OUT YEAR_NUMBER;MONTH:OUT MONTH_NUMBER;DAY:OUT DAY_NUMBER;SECONDS:OUT DAY_DURATION)IS
DAYS:INTEGER:=DAY_COUNT(DATE);
JD:INTEGER:=EPOCH+DAYS;
A:INTEGER:=JD+32044;
B:INTEGER:=(4*A+3)/146097;
C:INTEGER:=A-146097*B/4;
DD:INTEGER:=(4*C+3)/1461;
E:INTEGER:=C-1461*DD/4;
M:INTEGER:=(5*E+2)/153;
BEGIN
DAY:=E-(153*M+2)/5+1;
MONTH:=M+3-12*(M/10);
YEAR:=100*B+DD-4800+M/10;
SECONDS:=DURATION(DATE)-DURATION(DAYS)*DAY_SECONDS;
END SPLIT;

FUNCTION YEAR(DATE:TIME)RETURN YEAR_NUMBER IS
Y:YEAR_NUMBER;M:MONTH_NUMBER;D:DAY_NUMBER;S:DAY_DURATION;
BEGIN
SPLIT(DATE,Y,M,D,S);
RETURN Y;
END YEAR;

FUNCTION MONTH(DATE:TIME)RETURN MONTH_NUMBER IS
Y:YEAR_NUMBER;M:MONTH_NUMBER;D:DAY_NUMBER;S:DAY_DURATION;
BEGIN
SPLIT(DATE,Y,M,D,S);
RETURN M;
END MONTH;

FUNCTION DAY(DATE:TIME)RETURN DAY_NUMBER IS
Y:YEAR_NUMBER;M:MONTH_NUMBER;D:DAY_NUMBER;S:DAY_DURATION;
BEGIN
SPLIT(DATE,Y,M,D,S);
RETURN D;
END DAY;

FUNCTION SECONDS(DATE:TIME)RETURN DAY_DURATION IS
Y:YEAR_NUMBER;M:MONTH_NUMBER;D:DAY_NUMBER;S:DAY_DURATION;
BEGIN
SPLIT(DATE,Y,M,D,S);
RETURN S;
END SECONDS;

FUNCTION TIME_OF(YEAR:YEAR_NUMBER;MONTH:MONTH_NUMBER;DAY:DAY_NUMBER;SECONDS:DAY_DURATION:=0.0)RETURN TIME IS
DAYS_IN_MONTH:INTEGER;
BEGIN
CASE MONTH IS
WHEN 4|6|9|11=>DAYS_IN_MONTH:=30;
WHEN 2=>
IF YEAR MOD 4=0 AND THEN(YEAR MOD 100/=0 OR ELSE YEAR MOD 400=0)THEN
DAYS_IN_MONTH:=29;
ELSE
DAYS_IN_MONTH:=28;
END IF;
WHEN OTHERS=>DAYS_IN_MONTH:=31;
END CASE;
IF DAY>DAYS_IN_MONTH THEN RAISE TIME_ERROR;END IF;
RETURN TIME(DURATION(JULIAN_DAY(YEAR,MONTH,DAY)-EPOCH)*DAY_SECONDS+SECONDS);
END TIME_OF;

-- RM 9.6: "+" and "-" raise TIME_ERROR when the result is not a value of
-- type TIME. The bound is compared before adding so the check itself
-- cannot overflow the 64-bit mantissa.
FUNCTION "+"(LEFT:TIME;RIGHT:DURATION)RETURN TIME IS
L:DURATION:=DURATION(LEFT);
BEGIN
IF RIGHT>=0.0 THEN
IF L>TIME_LAST-RIGHT THEN RAISE TIME_ERROR;END IF;
ELSE
IF L<TIME_FIRST-RIGHT THEN RAISE TIME_ERROR;END IF;
END IF;
RETURN TIME(L+RIGHT);
END "+";

FUNCTION "+"(LEFT:DURATION;RIGHT:TIME)RETURN TIME IS
BEGIN
RETURN RIGHT+LEFT;
END "+";

FUNCTION "-"(LEFT:TIME;RIGHT:DURATION)RETURN TIME IS
L:DURATION:=DURATION(LEFT);
BEGIN
IF RIGHT>=0.0 THEN
IF L<TIME_FIRST+RIGHT THEN RAISE TIME_ERROR;END IF;
ELSE
IF L>TIME_LAST+RIGHT THEN RAISE TIME_ERROR;END IF;
END IF;
RETURN TIME(L-RIGHT);
END "-";

FUNCTION "-"(LEFT:TIME;RIGHT:TIME)RETURN DURATION IS
BEGIN
RETURN DURATION(LEFT)-DURATION(RIGHT);
END "-";

FUNCTION "<"(LEFT,RIGHT:TIME)RETURN BOOLEAN IS BEGIN RETURN DURATION(LEFT)<DURATION(RIGHT);END "<";
FUNCTION "<="(LEFT,RIGHT:TIME)RETURN BOOLEAN IS BEGIN RETURN DURATION(LEFT)<=DURATION(RIGHT);END "<=";
FUNCTION ">"(LEFT,RIGHT:TIME)RETURN BOOLEAN IS BEGIN RETURN DURATION(LEFT)>DURATION(RIGHT);END ">";
FUNCTION ">="(LEFT,RIGHT:TIME)RETURN BOOLEAN IS BEGIN RETURN DURATION(LEFT)>=DURATION(RIGHT);END ">=";

BEGIN
TIME_FIRST:=DURATION(JULIAN_DAY(1901,1,1)-EPOCH)*DAY_SECONDS;
TIME_LAST:=DURATION(JULIAN_DAY(2099,12,31)-EPOCH)*DAY_SECONDS+DAY_SECONDS;
END CALENDAR;
