PACKAGE CALENDAR IS
TYPE TIME IS PRIVATE;
SUBTYPE YEAR_NUMBER IS INTEGER RANGE 1901..2099;
SUBTYPE MONTH_NUMBER IS INTEGER RANGE 1..12;
SUBTYPE DAY_NUMBER IS INTEGER RANGE 1..31;
SUBTYPE DAY_DURATION IS DURATION RANGE 0.0..86_400.0;
FUNCTION CLOCK RETURN TIME;
FUNCTION YEAR(DATE:TIME)RETURN YEAR_NUMBER;
FUNCTION MONTH(DATE:TIME)RETURN MONTH_NUMBER;
FUNCTION DAY(DATE:TIME)RETURN DAY_NUMBER;
FUNCTION SECONDS(DATE:TIME)RETURN DAY_DURATION;
PROCEDURE SPLIT(DATE:IN TIME;YEAR:OUT YEAR_NUMBER;MONTH:OUT MONTH_NUMBER;DAY:OUT DAY_NUMBER;SECONDS:OUT DAY_DURATION);
FUNCTION TIME_OF(YEAR:YEAR_NUMBER;MONTH:MONTH_NUMBER;DAY:DAY_NUMBER;SECONDS:DAY_DURATION:=0.0)RETURN TIME;
FUNCTION "+"(LEFT:TIME;RIGHT:DURATION)RETURN TIME;
FUNCTION "+"(LEFT:DURATION;RIGHT:TIME)RETURN TIME;
FUNCTION "-"(LEFT:TIME;RIGHT:DURATION)RETURN TIME;
FUNCTION "-"(LEFT:TIME;RIGHT:TIME)RETURN DURATION;
FUNCTION "<"(LEFT,RIGHT:TIME)RETURN BOOLEAN;
FUNCTION "<="(LEFT,RIGHT:TIME)RETURN BOOLEAN;
FUNCTION ">"(LEFT,RIGHT:TIME)RETURN BOOLEAN;
FUNCTION ">="(LEFT,RIGHT:TIME)RETURN BOOLEAN;
TIME_ERROR:EXCEPTION;
PRIVATE
TYPE TIME IS NEW DURATION;
END CALENDAR;
