PACKAGE BODY CALENDAR IS
FUNCTION CLOCK RETURN TIME IS BEGIN RETURN TIME(0.0);END;
FUNCTION YEAR(DATE:TIME)RETURN YEAR_NUMBER IS BEGIN RETURN 1901;END;
FUNCTION MONTH(DATE:TIME)RETURN MONTH_NUMBER IS BEGIN RETURN 1;END;
FUNCTION DAY(DATE:TIME)RETURN DAY_NUMBER IS BEGIN RETURN 1;END;
FUNCTION SECONDS(DATE:TIME)RETURN DAY_DURATION IS BEGIN RETURN 0.0;END;
PROCEDURE SPLIT(DATE:IN TIME;YEAR:OUT YEAR_NUMBER;MONTH:OUT MONTH_NUMBER;DAY:OUT DAY_NUMBER;SECONDS:OUT DAY_DURATION)IS BEGIN YEAR:=1901;MONTH:=1;DAY:=1;SECONDS:=0.0;END;
FUNCTION TIME_OF(YEAR:YEAR_NUMBER;MONTH:MONTH_NUMBER;DAY:DAY_NUMBER;SECONDS:DAY_DURATION:=0.0)RETURN TIME IS BEGIN RETURN TIME(0.0);END;
FUNCTION "+"(LEFT:TIME;RIGHT:DURATION)RETURN TIME IS BEGIN RETURN TIME(DURATION(LEFT)+RIGHT);END;
FUNCTION "+"(LEFT:DURATION;RIGHT:TIME)RETURN TIME IS BEGIN RETURN TIME(LEFT+DURATION(RIGHT));END;
FUNCTION "-"(LEFT:TIME;RIGHT:DURATION)RETURN TIME IS BEGIN RETURN TIME(DURATION(LEFT)-RIGHT);END;
FUNCTION "-"(LEFT:TIME;RIGHT:TIME)RETURN DURATION IS BEGIN RETURN DURATION(LEFT)-DURATION(RIGHT);END;
FUNCTION "<"(LEFT,RIGHT:TIME)RETURN BOOLEAN IS BEGIN RETURN DURATION(LEFT)<DURATION(RIGHT);END;
FUNCTION "<="(LEFT,RIGHT:TIME)RETURN BOOLEAN IS BEGIN RETURN DURATION(LEFT)<=DURATION(RIGHT);END;
FUNCTION ">"(LEFT,RIGHT:TIME)RETURN BOOLEAN IS BEGIN RETURN DURATION(LEFT)>DURATION(RIGHT);END;
FUNCTION ">="(LEFT,RIGHT:TIME)RETURN BOOLEAN IS BEGIN RETURN DURATION(LEFT)>=DURATION(RIGHT);END;
END CALENDAR;
