PACKAGE BODY DIRECT_IO IS
TYPE FILE_INFO IS RECORD
FD:INTEGER;
M:FILE_MODE;
IDX:POSITIVE_COUNT;
SZ:COUNT;
OPEN:BOOLEAN;
END RECORD;
TYPE FILE_TABLE IS ARRAY(0..15)OF FILE_INFO;
FILES:FILE_TABLE;
NEXT_FD:INTEGER:=3;
PROCEDURE CREATE(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE:=INOUT_FILE;NAME:IN STRING:="";FORM:IN STRING:="")IS
BEGIN
IF NEXT_FD>15 THEN RAISE USE_ERROR;END IF;
FILES(NEXT_FD):=(NEXT_FD,MODE,1,0,TRUE);
FILE:=FILE_TYPE(NEXT_FD);
NEXT_FD:=NEXT_FD+1;
END CREATE;
PROCEDURE OPEN(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE;NAME:IN STRING;FORM:IN STRING:="")IS
BEGIN
IF NEXT_FD>15 THEN RAISE USE_ERROR;END IF;
FILES(NEXT_FD):=(NEXT_FD,MODE,1,0,TRUE);
FILE:=FILE_TYPE(NEXT_FD);
NEXT_FD:=NEXT_FD+1;
END OPEN;
PROCEDURE CLOSE(FILE:IN OUT FILE_TYPE)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).OPEN:=FALSE;END IF;
END CLOSE;
PROCEDURE DELETE(FILE:IN OUT FILE_TYPE)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).OPEN:=FALSE;FILES(I).SZ:=0;END IF;
END DELETE;
PROCEDURE RESET(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN
IF NOT FILES(I).OPEN THEN RAISE STATUS_ERROR;END IF;
FILES(I).M:=MODE;
FILES(I).IDX:=1;
END IF;
END RESET;
PROCEDURE RESET(FILE:IN OUT FILE_TYPE)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN
IF NOT FILES(I).OPEN THEN RAISE STATUS_ERROR;END IF;
FILES(I).IDX:=1;
END IF;
END RESET;
FUNCTION MODE(FILE:IN FILE_TYPE)RETURN FILE_MODE IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN
IF NOT FILES(I).OPEN THEN RAISE STATUS_ERROR;END IF;
RETURN FILES(I).M;
END IF;
RETURN IN_FILE;
END MODE;
FUNCTION NAME(FILE:IN FILE_TYPE)RETURN STRING IS BEGIN RETURN "";END NAME;
FUNCTION FORM(FILE:IN FILE_TYPE)RETURN STRING IS BEGIN RETURN "";END FORM;
FUNCTION IS_OPEN(FILE:IN FILE_TYPE)RETURN BOOLEAN IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN RETURN FILES(I).OPEN;END IF;
RETURN FALSE;
END IS_OPEN;
PROCEDURE READ(FILE:IN FILE_TYPE;ITEM:OUT ELEMENT_TYPE;FROM:IN POSITIVE_COUNT)IS
BEGIN
RAISE END_ERROR;
END READ;
PROCEDURE READ(FILE:IN FILE_TYPE;ITEM:OUT ELEMENT_TYPE)IS
BEGIN
RAISE END_ERROR;
END READ;
PROCEDURE WRITE(FILE:IN FILE_TYPE;ITEM:IN ELEMENT_TYPE;TO:IN POSITIVE_COUNT)IS
BEGIN
NULL;
END WRITE;
PROCEDURE WRITE(FILE:IN FILE_TYPE;ITEM:IN ELEMENT_TYPE)IS
BEGIN
NULL;
END WRITE;
PROCEDURE SET_INDEX(FILE:IN FILE_TYPE;TO:IN POSITIVE_COUNT)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN
IF NOT FILES(I).OPEN THEN RAISE STATUS_ERROR;END IF;
FILES(I).IDX:=TO;
END IF;
END SET_INDEX;
FUNCTION INDEX(FILE:IN FILE_TYPE)RETURN POSITIVE_COUNT IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN
IF NOT FILES(I).OPEN THEN RAISE STATUS_ERROR;END IF;
RETURN FILES(I).IDX;
END IF;
RETURN 1;
END INDEX;
FUNCTION SIZE(FILE:IN FILE_TYPE)RETURN COUNT IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN
IF NOT FILES(I).OPEN THEN RAISE STATUS_ERROR;END IF;
RETURN FILES(I).SZ;
END IF;
RETURN 0;
END SIZE;
FUNCTION END_OF_FILE(FILE:IN FILE_TYPE)RETURN BOOLEAN IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN
IF NOT FILES(I).OPEN THEN RAISE STATUS_ERROR;END IF;
RETURN FILES(I).IDX>FILES(I).SZ;
END IF;
RETURN TRUE;
END END_OF_FILE;
BEGIN
FOR I IN 0..15 LOOP
FILES(I):=(-1,IN_FILE,1,0,FALSE);
END LOOP;
FILES(0):=(0,INOUT_FILE,1,0,TRUE);
FILES(1):=(1,INOUT_FILE,1,0,TRUE);
FILES(2):=(2,INOUT_FILE,1,0,TRUE);
END DIRECT_IO;
