GENERIC
TYPE ELEMENT_TYPE IS PRIVATE;
PACKAGE DIRECT_IO IS
TYPE FILE_TYPE IS LIMITED PRIVATE;
TYPE FILE_MODE IS(IN_FILE,INOUT_FILE,OUT_FILE);
TYPE COUNT IS RANGE 0..INTEGER'LAST;
SUBTYPE POSITIVE_COUNT IS COUNT RANGE 1..COUNT'LAST;
STATUS_ERROR:EXCEPTION;
MODE_ERROR:EXCEPTION;
NAME_ERROR:EXCEPTION;
USE_ERROR:EXCEPTION;
DEVICE_ERROR:EXCEPTION;
END_ERROR:EXCEPTION;
DATA_ERROR:EXCEPTION;
PROCEDURE CREATE(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE:=INOUT_FILE;NAME:IN STRING:="";FORM:IN STRING:="");
PROCEDURE OPEN(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE;NAME:IN STRING;FORM:IN STRING:="");
PROCEDURE CLOSE(FILE:IN OUT FILE_TYPE);
PROCEDURE DELETE(FILE:IN OUT FILE_TYPE);
PROCEDURE RESET(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE);
PROCEDURE RESET(FILE:IN OUT FILE_TYPE);
FUNCTION MODE(FILE:IN FILE_TYPE)RETURN FILE_MODE;
FUNCTION NAME(FILE:IN FILE_TYPE)RETURN STRING;
FUNCTION FORM(FILE:IN FILE_TYPE)RETURN STRING;
FUNCTION IS_OPEN(FILE:IN FILE_TYPE)RETURN BOOLEAN;
PROCEDURE READ(FILE:IN FILE_TYPE;ITEM:OUT ELEMENT_TYPE;FROM:IN POSITIVE_COUNT);
PROCEDURE READ(FILE:IN FILE_TYPE;ITEM:OUT ELEMENT_TYPE);
PROCEDURE WRITE(FILE:IN FILE_TYPE;ITEM:IN ELEMENT_TYPE;TO:IN POSITIVE_COUNT);
PROCEDURE WRITE(FILE:IN FILE_TYPE;ITEM:IN ELEMENT_TYPE);
PROCEDURE SET_INDEX(FILE:IN FILE_TYPE;TO:IN POSITIVE_COUNT);
FUNCTION INDEX(FILE:IN FILE_TYPE)RETURN POSITIVE_COUNT;
FUNCTION SIZE(FILE:IN FILE_TYPE)RETURN COUNT;
FUNCTION END_OF_FILE(FILE:IN FILE_TYPE)RETURN BOOLEAN;
PRIVATE
TYPE FILE_TYPE IS NEW INTEGER;
END DIRECT_IO;
