PACKAGE INTERFACES IS
TYPE INTEGER_8 IS RANGE -(2**7)..2**7-1;
TYPE INTEGER_16 IS RANGE -(2**15)..2**15-1;
TYPE INTEGER_32 IS RANGE -(2**31)..2**31-1;
TYPE UNSIGNED_8 IS RANGE 0..2**8-1;
TYPE UNSIGNED_16 IS RANGE 0..2**16-1;
TYPE UNSIGNED_32 IS RANGE 0..2**32-1;
FUNCTION SHIFT_LEFT(VALUE:UNSIGNED_32;AMOUNT:NATURAL)RETURN UNSIGNED_32;
FUNCTION SHIFT_RIGHT(VALUE:UNSIGNED_32;AMOUNT:NATURAL)RETURN UNSIGNED_32;
FUNCTION SHIFT_RIGHT_ARITHMETIC(VALUE:UNSIGNED_32;AMOUNT:NATURAL)RETURN UNSIGNED_32;
FUNCTION ROTATE_LEFT(VALUE:UNSIGNED_32;AMOUNT:NATURAL)RETURN UNSIGNED_32;
FUNCTION ROTATE_RIGHT(VALUE:UNSIGNED_32;AMOUNT:NATURAL)RETURN UNSIGNED_32;
END INTERFACES;
