PACKAGE BODY INTERFACES IS
FUNCTION __INTERFACES_SHIFT_LEFT(V:INTEGER;N:INTEGER)RETURN INTEGER;
PRAGMA IMPORT(C,__INTERFACES_SHIFT_LEFT);
FUNCTION __INTERFACES_SHIFT_RIGHT(V:INTEGER;N:INTEGER)RETURN INTEGER;
PRAGMA IMPORT(C,__INTERFACES_SHIFT_RIGHT);
FUNCTION __INTERFACES_SHIFT_RIGHT_ARITHMETIC(V:INTEGER;N:INTEGER)RETURN INTEGER;
PRAGMA IMPORT(C,__INTERFACES_SHIFT_RIGHT_ARITHMETIC);
FUNCTION __INTERFACES_ROTATE_LEFT(V:INTEGER;N:INTEGER)RETURN INTEGER;
PRAGMA IMPORT(C,__INTERFACES_ROTATE_LEFT);
FUNCTION __INTERFACES_ROTATE_RIGHT(V:INTEGER;N:INTEGER)RETURN INTEGER;
PRAGMA IMPORT(C,__INTERFACES_ROTATE_RIGHT);
FUNCTION SHIFT_LEFT(VALUE:UNSIGNED_32;AMOUNT:NATURAL)RETURN UNSIGNED_32 IS BEGIN RETURN UNSIGNED_32(__INTERFACES_SHIFT_LEFT(INTEGER(VALUE),AMOUNT));END;
FUNCTION SHIFT_RIGHT(VALUE:UNSIGNED_32;AMOUNT:NATURAL)RETURN UNSIGNED_32 IS BEGIN RETURN UNSIGNED_32(__INTERFACES_SHIFT_RIGHT(INTEGER(VALUE),AMOUNT));END;
FUNCTION SHIFT_RIGHT_ARITHMETIC(VALUE:UNSIGNED_32;AMOUNT:NATURAL)RETURN UNSIGNED_32 IS BEGIN RETURN UNSIGNED_32(__INTERFACES_SHIFT_RIGHT_ARITHMETIC(INTEGER(VALUE),AMOUNT));END;
FUNCTION ROTATE_LEFT(VALUE:UNSIGNED_32;AMOUNT:NATURAL)RETURN UNSIGNED_32 IS BEGIN RETURN UNSIGNED_32(__INTERFACES_ROTATE_LEFT(INTEGER(VALUE),AMOUNT));END;
FUNCTION ROTATE_RIGHT(VALUE:UNSIGNED_32;AMOUNT:NATURAL)RETURN UNSIGNED_32 IS BEGIN RETURN UNSIGNED_32(__INTERFACES_ROTATE_RIGHT(INTEGER(VALUE),AMOUNT));END;
END INTERFACES;
