PACKAGE IO_EXCEPTIONS IS
STATUS_ERROR:EXCEPTION;
MODE_ERROR:EXCEPTION;
NAME_ERROR:EXCEPTION;
USE_ERROR:EXCEPTION;
DEVICE_ERROR:EXCEPTION;
END_ERROR:EXCEPTION;
DATA_ERROR:EXCEPTION;
LAYOUT_ERROR:EXCEPTION;
END IO_EXCEPTIONS;
