PACKAGE BODY LOW_LEVEL_IO IS
PROCEDURE SEND_CONTROL(DEVICE:IN INTEGER;DATA:IN BYTE_ARRAY)IS BEGIN NULL;END;
PROCEDURE RECEIVE_CONTROL(DEVICE:IN INTEGER;DATA:OUT BYTE_ARRAY)IS BEGIN NULL;END;
END LOW_LEVEL_IO;
