PACKAGE LOW_LEVEL_IO IS
TYPE DEVICE IS NEW INTEGER;
TYPE DATA IS NEW INTEGER;
PROCEDURE SEND_CONTROL(DEVICE:IN DEVICE;DATA:IN OUT DATA);
PROCEDURE RECEIVE_CONTROL(DEVICE:IN DEVICE;DATA:IN OUT DATA);
END LOW_LEVEL_IO;
