PACKAGE BODY LOW_LEVEL_IO IS
PROCEDURE SEND_CONTROL(DEVICE:IN DEVICE;DATA:IN OUT DATA)IS BEGIN NULL;END SEND_CONTROL;
PROCEDURE RECEIVE_CONTROL(DEVICE:IN DEVICE;DATA:IN OUT DATA)IS BEGIN NULL;END RECEIVE_CONTROL;
END LOW_LEVEL_IO;
