PACKAGE BODY LOW_LEVEL_IO IS
LAST_DEVICE:DEVICE:=0;
LAST_SEND:DATA:=0;
LAST_RECEIVE:DATA:=0;
PROCEDURE SEND_CONTROL(DEVICE:IN DEVICE;DATA:IN OUT DATA)IS
BEGIN
LAST_DEVICE:=DEVICE;
LAST_SEND:=DATA;
DATA:=DATA+1;
END SEND_CONTROL;
PROCEDURE RECEIVE_CONTROL(DEVICE:IN DEVICE;DATA:IN OUT DATA)IS
BEGIN
LAST_DEVICE:=DEVICE;
LAST_RECEIVE:=DATA;
DATA:=LAST_SEND;
END RECEIVE_CONTROL;
END LOW_LEVEL_IO;
