PACKAGE LOW_LEVEL_IO IS
SUBTYPE BYTE IS INTEGER RANGE 0..255;
TYPE BYTE_ARRAY IS ARRAY(INTEGER RANGE<>)OF BYTE;
PROCEDURE SEND_CONTROL(DEVICE:IN INTEGER;DATA:IN BYTE_ARRAY);
PROCEDURE RECEIVE_CONTROL(DEVICE:IN INTEGER;DATA:OUT BYTE_ARRAY);
END LOW_LEVEL_IO;
