PACKAGE MACHINE_CODE IS
TYPE INSTRUCTION IS PRIVATE;
TYPE OPERAND IS PRIVATE;
TYPE REGISTER IS(EAX,EBX,ECX,EDX,ESI,EDI,EBP,ESP,RAX,RBX,RCX,RDX,RSI,RDI,RBP,RSP,R8,R9,R10,R11,R12,R13,R14,R15);
PROCEDURE CODE(OP:IN STRING;DST:IN REGISTER;SRC:IN REGISTER);
PROCEDURE CODE(OP:IN STRING;DST:IN REGISTER;SRC:IN INTEGER);
PROCEDURE CODE(OP:IN STRING;DST:IN REGISTER);
PROCEDURE CODE(OP:IN STRING);
PRIVATE
TYPE INSTRUCTION IS NEW INTEGER;
TYPE OPERAND IS NEW INTEGER;
END MACHINE_CODE;
