PACKAGE BODY MACHINE_CODE IS
PROCEDURE CODE(OP:IN STRING;DST:IN REGISTER;SRC:IN REGISTER)IS BEGIN NULL;END;
PROCEDURE CODE(OP:IN STRING;DST:IN REGISTER;SRC:IN INTEGER)IS BEGIN NULL;END;
PROCEDURE CODE(OP:IN STRING;DST:IN REGISTER)IS BEGIN NULL;END;
PROCEDURE CODE(OP:IN STRING)IS BEGIN NULL;END;
END MACHINE_CODE;
