
PACKAGE MACHINE_CODE IS

   TYPE ASSEMBLER_INSERTION
          (TEMPLATE_LENGTH : POSITIVE;
           CLOBBER_LENGTH  : NATURAL) IS
      RECORD
         TEMPLATE : STRING (1 .. TEMPLATE_LENGTH);
         CLOBBERS : STRING (1 .. CLOBBER_LENGTH);
      END RECORD;

   TYPE INTEL_INSERTION
          (TEMPLATE_LENGTH : POSITIVE;
           CLOBBER_LENGTH  : NATURAL) IS
      RECORD
         TEMPLATE : STRING (1 .. TEMPLATE_LENGTH);
         CLOBBERS : STRING (1 .. CLOBBER_LENGTH);
      END RECORD;

   TYPE INTERMEDIATE_INSERTION
          (TEXT_LENGTH : POSITIVE) IS
      RECORD
         TEXT : STRING (1 .. TEXT_LENGTH);
      END RECORD;

END MACHINE_CODE;
