PACKAGE BODY SEQUENTIAL_IO IS
PROCEDURE CREATE(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE:=OUT_FILE;NAME:IN STRING:="";FORM:IN STRING:="")IS BEGIN NULL;END;
PROCEDURE OPEN(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE;NAME:IN STRING;FORM:IN STRING:="")IS BEGIN NULL;END;
PROCEDURE CLOSE(FILE:IN OUT FILE_TYPE)IS BEGIN NULL;END;
PROCEDURE DELETE(FILE:IN OUT FILE_TYPE)IS BEGIN NULL;END;
PROCEDURE RESET(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE)IS BEGIN NULL;END;
PROCEDURE RESET(FILE:IN OUT FILE_TYPE)IS BEGIN NULL;END;
FUNCTION MODE(FILE:IN FILE_TYPE)RETURN FILE_MODE IS BEGIN RETURN IN_FILE;END;
FUNCTION NAME(FILE:IN FILE_TYPE)RETURN STRING IS BEGIN RETURN "";END;
FUNCTION FORM(FILE:IN FILE_TYPE)RETURN STRING IS BEGIN RETURN "";END;
FUNCTION IS_OPEN(FILE:IN FILE_TYPE)RETURN BOOLEAN IS BEGIN RETURN FALSE;END;
PROCEDURE READ(FILE:IN FILE_TYPE;ITEM:OUT ELEMENT_TYPE)IS BEGIN NULL;END;
PROCEDURE WRITE(FILE:IN FILE_TYPE;ITEM:IN ELEMENT_TYPE)IS BEGIN NULL;END;
FUNCTION END_OF_FILE(FILE:IN FILE_TYPE)RETURN BOOLEAN IS BEGIN RETURN FALSE;END;
END SEQUENTIAL_IO;
