PACKAGE BODY TEXT_IO IS
TYPE FILE_RECORD IS RECORD
FD:INTEGER;
M:FILE_MODE;
LN:COUNT;
PG:COUNT;
CL:COUNT;
END RECORD;
TYPE FILE_ARRAY IS ARRAY(0..15)OF FILE_RECORD;
FILES:FILE_ARRAY;
NEXT_FD:INTEGER:=3;
PROCEDURE CREATE(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE:=OUT_FILE;NAME:IN STRING:="";FORM:IN STRING:="")IS
BEGIN
IF NEXT_FD>15 THEN RAISE USE_ERROR;END IF;
FILES(NEXT_FD):=(NEXT_FD,MODE,1,1,1);
FILE:=FILE_TYPE(NEXT_FD);
NEXT_FD:=NEXT_FD+1;
END CREATE;
PROCEDURE OPEN(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE;NAME:IN STRING;FORM:IN STRING:="")IS
BEGIN
IF NEXT_FD>15 THEN RAISE USE_ERROR;END IF;
FILES(NEXT_FD):=(NEXT_FD,MODE,1,1,1);
FILE:=FILE_TYPE(NEXT_FD);
NEXT_FD:=NEXT_FD+1;
END OPEN;
PROCEDURE CLOSE(FILE:IN OUT FILE_TYPE)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).FD:=-1;END IF;
END CLOSE;
PROCEDURE DELETE(FILE:IN OUT FILE_TYPE)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).FD:=-1;END IF;
END DELETE;
PROCEDURE RESET(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I):=(I,MODE,1,1,1);END IF;
END RESET;
PROCEDURE RESET(FILE:IN OUT FILE_TYPE)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).LN:=1;FILES(I).PG:=1;FILES(I).CL:=1;END IF;
END RESET;
FUNCTION MODE(FILE:IN FILE_TYPE)RETURN FILE_MODE IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN RETURN FILES(I).M;END IF;
RETURN IN_FILE;
END MODE;
FUNCTION NAME(FILE:IN FILE_TYPE)RETURN STRING IS BEGIN RETURN "";END NAME;
FUNCTION FORM(FILE:IN FILE_TYPE)RETURN STRING IS BEGIN RETURN "";END FORM;
FUNCTION IS_OPEN(FILE:IN FILE_TYPE)RETURN BOOLEAN IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN RETURN FILES(I).FD>=0;END IF;
RETURN FALSE;
END IS_OPEN;
PROCEDURE SET_INPUT(FILE:IN FILE_TYPE)IS BEGIN NULL;END SET_INPUT;
PROCEDURE SET_OUTPUT(FILE:IN FILE_TYPE)IS BEGIN NULL;END SET_OUTPUT;
PROCEDURE SET_ERROR(FILE:IN FILE_TYPE)IS BEGIN NULL;END SET_ERROR;
FUNCTION STANDARD_INPUT RETURN FILE_TYPE IS BEGIN RETURN FILE_TYPE(0);END STANDARD_INPUT;
FUNCTION STANDARD_OUTPUT RETURN FILE_TYPE IS BEGIN RETURN FILE_TYPE(1);END STANDARD_OUTPUT;
FUNCTION STANDARD_ERROR RETURN FILE_TYPE IS BEGIN RETURN FILE_TYPE(2);END STANDARD_ERROR;
FUNCTION CURRENT_INPUT RETURN FILE_TYPE IS BEGIN RETURN FILE_TYPE(0);END CURRENT_INPUT;
FUNCTION CURRENT_OUTPUT RETURN FILE_TYPE IS BEGIN RETURN FILE_TYPE(1);END CURRENT_OUTPUT;
FUNCTION CURRENT_ERROR RETURN FILE_TYPE IS BEGIN RETURN FILE_TYPE(2);END CURRENT_ERROR;
PROCEDURE FLUSH(FILE:IN FILE_TYPE)IS BEGIN NULL;END FLUSH;
PROCEDURE FLUSH IS BEGIN NULL;END FLUSH;
PROCEDURE SET_LINE_LENGTH(FILE:IN FILE_TYPE;TO:IN COUNT)IS BEGIN NULL;END SET_LINE_LENGTH;
PROCEDURE SET_LINE_LENGTH(TO:IN COUNT)IS BEGIN NULL;END SET_LINE_LENGTH;
PROCEDURE SET_PAGE_LENGTH(FILE:IN FILE_TYPE;TO:IN COUNT)IS BEGIN NULL;END SET_PAGE_LENGTH;
PROCEDURE SET_PAGE_LENGTH(TO:IN COUNT)IS BEGIN NULL;END SET_PAGE_LENGTH;
FUNCTION LINE_LENGTH(FILE:IN FILE_TYPE)RETURN COUNT IS BEGIN RETURN 80;END LINE_LENGTH;
FUNCTION LINE_LENGTH RETURN COUNT IS BEGIN RETURN 80;END LINE_LENGTH;
FUNCTION PAGE_LENGTH(FILE:IN FILE_TYPE)RETURN COUNT IS BEGIN RETURN 60;END PAGE_LENGTH;
FUNCTION PAGE_LENGTH RETURN COUNT IS BEGIN RETURN 60;END PAGE_LENGTH;
PROCEDURE NEW_LINE(FILE:IN FILE_TYPE;SPACING:IN POSITIVE_COUNT:=1)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN
FOR J IN 1..SPACING LOOP
FILES(I).LN:=FILES(I).LN+1;
FILES(I).CL:=1;
END LOOP;
END IF;
END NEW_LINE;
PROCEDURE NEW_LINE(SPACING:IN POSITIVE_COUNT:=1)IS BEGIN NEW_LINE(STANDARD_OUTPUT,SPACING);END NEW_LINE;
PROCEDURE SKIP_LINE(FILE:IN FILE_TYPE;SPACING:IN POSITIVE_COUNT:=1)IS BEGIN NULL;END SKIP_LINE;
PROCEDURE SKIP_LINE(SPACING:IN POSITIVE_COUNT:=1)IS BEGIN NULL;END SKIP_LINE;
FUNCTION END_OF_LINE(FILE:IN FILE_TYPE)RETURN BOOLEAN IS BEGIN RETURN FALSE;END END_OF_LINE;
FUNCTION END_OF_LINE RETURN BOOLEAN IS BEGIN RETURN FALSE;END END_OF_LINE;
PROCEDURE NEW_PAGE(FILE:IN FILE_TYPE)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).PG:=FILES(I).PG+1;FILES(I).LN:=1;FILES(I).CL:=1;END IF;
END NEW_PAGE;
PROCEDURE NEW_PAGE IS BEGIN NEW_PAGE(STANDARD_OUTPUT);END NEW_PAGE;
PROCEDURE SKIP_PAGE(FILE:IN FILE_TYPE)IS BEGIN NULL;END SKIP_PAGE;
PROCEDURE SKIP_PAGE IS BEGIN NULL;END SKIP_PAGE;
FUNCTION END_OF_PAGE(FILE:IN FILE_TYPE)RETURN BOOLEAN IS BEGIN RETURN FALSE;END END_OF_PAGE;
FUNCTION END_OF_PAGE RETURN BOOLEAN IS BEGIN RETURN FALSE;END END_OF_PAGE;
FUNCTION END_OF_FILE(FILE:IN FILE_TYPE)RETURN BOOLEAN IS BEGIN RETURN FALSE;END END_OF_FILE;
FUNCTION END_OF_FILE RETURN BOOLEAN IS BEGIN RETURN FALSE;END END_OF_FILE;
PROCEDURE SET_COL(FILE:IN FILE_TYPE;TO:IN POSITIVE_COUNT)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).CL:=TO;END IF;
END SET_COL;
PROCEDURE SET_COL(TO:IN POSITIVE_COUNT)IS BEGIN SET_COL(STANDARD_OUTPUT,TO);END SET_COL;
PROCEDURE SET_LINE(FILE:IN FILE_TYPE;TO:IN POSITIVE_COUNT)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).LN:=TO;END IF;
END SET_LINE;
PROCEDURE SET_LINE(TO:IN POSITIVE_COUNT)IS BEGIN SET_LINE(STANDARD_OUTPUT,TO);END SET_LINE;
FUNCTION COL(FILE:IN FILE_TYPE)RETURN POSITIVE_COUNT IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN RETURN FILES(I).CL;END IF;
RETURN 1;
END COL;
FUNCTION COL RETURN POSITIVE_COUNT IS BEGIN RETURN COL(STANDARD_OUTPUT);END COL;
FUNCTION LINE(FILE:IN FILE_TYPE)RETURN POSITIVE_COUNT IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN RETURN FILES(I).LN;END IF;
RETURN 1;
END LINE;
FUNCTION LINE RETURN POSITIVE_COUNT IS BEGIN RETURN LINE(STANDARD_OUTPUT);END LINE;
FUNCTION PAGE(FILE:IN FILE_TYPE)RETURN POSITIVE_COUNT IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN RETURN FILES(I).PG;END IF;
RETURN 1;
END PAGE;
FUNCTION PAGE RETURN POSITIVE_COUNT IS BEGIN RETURN PAGE(STANDARD_OUTPUT);END PAGE;
PROCEDURE GET(FILE:IN FILE_TYPE;ITEM:OUT CHARACTER)IS BEGIN ITEM:=' ';END GET;
PROCEDURE GET(ITEM:OUT CHARACTER)IS BEGIN ITEM:=' ';END GET;
PROCEDURE PUT(FILE:IN FILE_TYPE;ITEM:IN CHARACTER)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).CL:=FILES(I).CL+1;END IF;
END PUT;
PROCEDURE PUT(ITEM:IN CHARACTER)IS BEGIN PUT(STANDARD_OUTPUT,ITEM);END PUT;
PROCEDURE GET(FILE:IN FILE_TYPE;ITEM:OUT STRING)IS BEGIN NULL;END GET;
PROCEDURE GET(ITEM:OUT STRING)IS BEGIN NULL;END GET;
PROCEDURE PUT(FILE:IN FILE_TYPE;ITEM:IN STRING)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).CL:=FILES(I).CL+COUNT(ITEM'LENGTH);END IF;
END PUT;
PROCEDURE PUT(ITEM:IN STRING)IS BEGIN PUT(STANDARD_OUTPUT,ITEM);END PUT;
PROCEDURE GET_LINE(FILE:IN FILE_TYPE;ITEM:OUT STRING;LAST:OUT NATURAL)IS BEGIN LAST:=0;END GET_LINE;
PROCEDURE GET_LINE(ITEM:OUT STRING;LAST:OUT NATURAL)IS BEGIN LAST:=0;END GET_LINE;
PROCEDURE PUT_LINE(FILE:IN FILE_TYPE;ITEM:IN STRING)IS BEGIN PUT(FILE,ITEM);NEW_LINE(FILE);END PUT_LINE;
PROCEDURE PUT_LINE(ITEM:IN STRING)IS BEGIN PUT(ITEM);NEW_LINE;END PUT_LINE;
PACKAGE BODY INTEGER_IO IS
PROCEDURE GET(FILE:IN FILE_TYPE;ITEM:OUT NUM;WIDTH:IN FIELD:=0)IS BEGIN ITEM:=NUM'FIRST;END GET;
PROCEDURE GET(ITEM:OUT NUM;WIDTH:IN FIELD:=0)IS BEGIN ITEM:=NUM'FIRST;END GET;
PROCEDURE PUT(FILE:IN FILE_TYPE;ITEM:IN NUM;WIDTH:IN FIELD:=DEFAULT_WIDTH;BASE:IN NUMBER_BASE:=DEFAULT_BASE)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).CL:=FILES(I).CL+COUNT(WIDTH);END IF;
END PUT;
PROCEDURE PUT(ITEM:IN NUM;WIDTH:IN FIELD:=DEFAULT_WIDTH;BASE:IN NUMBER_BASE:=DEFAULT_BASE)IS BEGIN PUT(STANDARD_OUTPUT,ITEM,WIDTH,BASE);END PUT;
PROCEDURE GET(FROM:IN STRING;ITEM:OUT NUM;LAST:OUT POSITIVE)IS BEGIN ITEM:=NUM'FIRST;LAST:=1;END GET;
PROCEDURE PUT(TO:OUT STRING;ITEM:IN NUM;BASE:IN NUMBER_BASE:=DEFAULT_BASE)IS BEGIN NULL;END PUT;
END INTEGER_IO;
PACKAGE BODY FLOAT_IO IS
PROCEDURE GET(FILE:IN FILE_TYPE;ITEM:OUT NUM;WIDTH:IN FIELD:=0)IS BEGIN ITEM:=0.0;END GET;
PROCEDURE GET(ITEM:OUT NUM;WIDTH:IN FIELD:=0)IS BEGIN ITEM:=0.0;END GET;
PROCEDURE PUT(FILE:IN FILE_TYPE;ITEM:IN NUM;FORE:IN FIELD:=DEFAULT_FORE;AFT:IN FIELD:=DEFAULT_AFT;EXP:IN FIELD:=DEFAULT_EXP)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).CL:=FILES(I).CL+COUNT(FORE+AFT+EXP+2);END IF;
END PUT;
PROCEDURE PUT(ITEM:IN NUM;FORE:IN FIELD:=DEFAULT_FORE;AFT:IN FIELD:=DEFAULT_AFT;EXP:IN FIELD:=DEFAULT_EXP)IS BEGIN PUT(STANDARD_OUTPUT,ITEM,FORE,AFT,EXP);END PUT;
PROCEDURE GET(FROM:IN STRING;ITEM:OUT NUM;LAST:OUT POSITIVE)IS BEGIN ITEM:=0.0;LAST:=1;END GET;
PROCEDURE PUT(TO:OUT STRING;ITEM:IN NUM;AFT:IN FIELD:=DEFAULT_AFT;EXP:IN FIELD:=DEFAULT_EXP)IS BEGIN NULL;END PUT;
END FLOAT_IO;
PACKAGE BODY FIXED_IO IS
PROCEDURE GET(FILE:IN FILE_TYPE;ITEM:OUT NUM;WIDTH:IN FIELD:=0)IS BEGIN ITEM:=0.0;END GET;
PROCEDURE GET(ITEM:OUT NUM;WIDTH:IN FIELD:=0)IS BEGIN ITEM:=0.0;END GET;
PROCEDURE PUT(FILE:IN FILE_TYPE;ITEM:IN NUM;FORE:IN FIELD:=DEFAULT_FORE;AFT:IN FIELD:=DEFAULT_AFT;EXP:IN FIELD:=DEFAULT_EXP)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).CL:=FILES(I).CL+COUNT(FORE+AFT+EXP+2);END IF;
END PUT;
PROCEDURE PUT(ITEM:IN NUM;FORE:IN FIELD:=DEFAULT_FORE;AFT:IN FIELD:=DEFAULT_AFT;EXP:IN FIELD:=DEFAULT_EXP)IS BEGIN PUT(STANDARD_OUTPUT,ITEM,FORE,AFT,EXP);END PUT;
PROCEDURE GET(FROM:IN STRING;ITEM:OUT NUM;LAST:OUT POSITIVE)IS BEGIN ITEM:=0.0;LAST:=1;END GET;
PROCEDURE PUT(TO:OUT STRING;ITEM:IN NUM;AFT:IN FIELD:=DEFAULT_AFT;EXP:IN FIELD:=DEFAULT_EXP)IS BEGIN NULL;END PUT;
END FIXED_IO;
PACKAGE BODY ENUMERATION_IO IS
PROCEDURE GET(FILE:IN FILE_TYPE;ITEM:OUT ENUM)IS BEGIN ITEM:=ENUM'FIRST;END GET;
PROCEDURE GET(ITEM:OUT ENUM)IS BEGIN ITEM:=ENUM'FIRST;END GET;
PROCEDURE PUT(FILE:IN FILE_TYPE;ITEM:IN ENUM;WIDTH:IN FIELD:=DEFAULT_WIDTH;SET:IN TYPE_SET:=DEFAULT_SETTING)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).CL:=FILES(I).CL+COUNT(WIDTH);END IF;
END PUT;
PROCEDURE PUT(ITEM:IN ENUM;WIDTH:IN FIELD:=DEFAULT_WIDTH;SET:IN TYPE_SET:=DEFAULT_SETTING)IS BEGIN PUT(STANDARD_OUTPUT,ITEM,WIDTH,SET);END PUT;
PROCEDURE GET(FROM:IN STRING;ITEM:OUT ENUM;LAST:OUT POSITIVE)IS BEGIN ITEM:=ENUM'FIRST;LAST:=1;END GET;
PROCEDURE PUT(TO:OUT STRING;ITEM:IN ENUM;SET:IN TYPE_SET:=DEFAULT_SETTING)IS BEGIN NULL;END PUT;
END ENUMERATION_IO;
END TEXT_IO;
