GENERIC
TYPE OBJECT IS LIMITED PRIVATE;
TYPE NAME IS ACCESS OBJECT;
PROCEDURE UNCHECKED_DEALLOCATION(X:IN OUT NAME);
PRAGMA CONVENTION(INTRINSIC,UNCHECKED_DEALLOCATION);
PRAGMA PURE(UNCHECKED_DEALLOCATION);
