GENERIC
TYPE SOURCE IS LIMITED PRIVATE;
TYPE TARGET IS LIMITED PRIVATE;
FUNCTION UNCHECKED_CONVERSION(S:SOURCE)RETURN TARGET;
PRAGMA CONVENTION(INTRINSIC,UNCHECKED_CONVERSION);
PRAGMA PURE(UNCHECKED_CONVERSION);
