-- FCNDECL.ADS

-- PACKAGE THAT MAY BE MODIFIED TO DECLARE FUNCTIONS THAT RETURN
-- VALUES USABLE FOR INITIALIZATION OF CONSTANTS IN PACKAGE SPPRT13.
--
-- This implementation backs each SPPRT13 address constant with a real
-- variable (see the body), so that FOR X USE AT <address> clauses overlay
-- storage that actually exists and tests may read and write through the
-- overlaid objects safely.

WITH SYSTEM;
PACKAGE FCNDECL IS

     FUNCTION VAR_ADDRESS  RETURN SYSTEM.ADDRESS;
     FUNCTION VAR_ADDRESS1 RETURN SYSTEM.ADDRESS;
     FUNCTION VAR_ADDRESS2 RETURN SYSTEM.ADDRESS;

     FUNCTION ENT_ADDRESS  RETURN SYSTEM.ADDRESS;
     FUNCTION ENT_ADDRESS1 RETURN SYSTEM.ADDRESS;
     FUNCTION ENT_ADDRESS2 RETURN SYSTEM.ADDRESS;

END FCNDECL;
