-- FCNDECL.ADB

-- Backing storage for the SPPRT13 address constants. Sized generously so
-- overlaid objects of composite types fit.

PACKAGE BODY FCNDECL IS

     TYPE BACKING IS ARRAY (1 .. 256) OF INTEGER;

     VAR_STORE  : BACKING;
     VAR_STORE1 : BACKING;
     VAR_STORE2 : BACKING;

     ENT_STORE  : BACKING;
     ENT_STORE1 : BACKING;
     ENT_STORE2 : BACKING;

     FUNCTION VAR_ADDRESS RETURN SYSTEM.ADDRESS IS
     BEGIN
          RETURN VAR_STORE'ADDRESS;
     END VAR_ADDRESS;

     FUNCTION VAR_ADDRESS1 RETURN SYSTEM.ADDRESS IS
     BEGIN
          RETURN VAR_STORE1'ADDRESS;
     END VAR_ADDRESS1;

     FUNCTION VAR_ADDRESS2 RETURN SYSTEM.ADDRESS IS
     BEGIN
          RETURN VAR_STORE2'ADDRESS;
     END VAR_ADDRESS2;

     FUNCTION ENT_ADDRESS RETURN SYSTEM.ADDRESS IS
     BEGIN
          RETURN ENT_STORE'ADDRESS;
     END ENT_ADDRESS;

     FUNCTION ENT_ADDRESS1 RETURN SYSTEM.ADDRESS IS
     BEGIN
          RETURN ENT_STORE1'ADDRESS;
     END ENT_ADDRESS1;

     FUNCTION ENT_ADDRESS2 RETURN SYSTEM.ADDRESS IS
     BEGIN
          RETURN ENT_STORE2'ADDRESS;
     END ENT_ADDRESS2;

END FCNDECL;
