PACKAGE REPORT IS
PROCEDURE TEST(NAME:STRING;DESC:STRING);
PROCEDURE FAILED(MSG:STRING);
PROCEDURE RESULT;
PROCEDURE COMMENT(MSG:STRING);
FUNCTION IDENT_INT(X:INTEGER)RETURN INTEGER;
FUNCTION IDENT_BOOL(X:BOOLEAN)RETURN BOOLEAN;
FUNCTION IDENT_CHAR(X:CHARACTER)RETURN CHARACTER;
FUNCTION IDENT_STR(X:STRING)RETURN STRING;
FUNCTION EQUAL(X,Y:INTEGER)RETURN BOOLEAN;
TYPE FILE_NUM IS RANGE 1..5;
FUNCTION LEGAL_FILE_NAME(X:FILE_NUM:=1;NAM:STRING:="")RETURN STRING;
PROCEDURE NOT_APPLICABLE(DESCR:STRING);
MAX_IN_LEN:CONSTANT INTEGER:=1000;
END REPORT;
